### ISSUE TITLE
[Bug]: The board information is not loaded/updated correctly in Snowboard Kids

### ISSUE THREAD

**Issue by dezraj** [project64/project64#2284] opened 2022-09-08 03:10 UTC
### Expected behavior?

When we select the Alpine or All Around board types, this board selection was supposed to work before and after the race starts.

### Actual behavior?

Currently when we select either All Around or Alpine board types, the program fails to load/update the board information and falls back to the Free Style board type. You can notice that as soon as you select one of these board types their shapes will change to the one we have in Free Style. This bug also affects the board function, that is, it indeed works as a Free Style board in the race, not as an All Around or Alpine one.

Short video-clip of the issue happening with the Alpine board type and comparing it with simple64 (former m64p):
https://drive.google.com/file/d/1IrDSW0pcSqd67QpqHvRonzvKqKIfA7VK/view?usp=sharing

It is impossible to advance in the game if we are unable to select the other board types.

### Steps to reproduce the problem

1. Run the game
2. Choose your character and then select Battle Race
3. Select a course
4. In the Board selection screen, select either All Around or Alpine and highlight Level 1
5. As soon as you hit A/Start in Level 1 you should see that the board shape changes to Free style
6. Pay attention to the board shape when you are in the race, it should indeed be the Free style type, not the All Around or Alpine ones
...

### Error messages?

None

### What game were you playing?

Title: Snowboard Kids

Nintendo 64 game or Nintendo 64 Disk Drive: Snowboard Kids

ROM information (First you must uncheck "hide advanced settings" in the settings menu, then File > ROM info should show up, post the information contained there in this field. Alternatively, you can right click the ROM in the ROM browser and hit "ROM information".):
![image](https://user-images.githubusercontent.com/27839354/189023511-627daa86-97fe-4f4a-b690-1492a58e3020.png)

Save type: (attach game save or save state here)

Original or modified ROM?:(attach patch if applicable here)

### Specifications and build details

Project64: (include commit version number and whether you are using the
32-bit or 64-bit version)
Project64-Dev-4.0.0-5911-a640ecf
OS: (include version and OS build number using WinVer):
Windows 10 17763.3287
CPU:
i5-10400
RAM:
16gb
Graphics:
GTX 1660 Ti

### Using included plugins

- [X] I can confirm I am using the included RSP, audio, input, and graphics plugins

### Plugins used while the issue occurred

All included plugins with all default settings.

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment] 2022-09-08 03:36
Works in interpreter. 
Broke with changes in 5889

**Comment by Squall-Leonhart** [comment] 2022-09-08 03:48
Temporarily disable Register Caching in the recompiler settings.

**Comment by Squall-Leonhart** [comment] 2022-11-14 11:59
Caused by compiler optimizations, as outlined by https://github.com/project64/project64/issues/2300

**Comment by Squall-Leonhart** [comment] 2022-11-25 03:14
Fixed by https://github.com/project64/project64/commit/e3aa2514c1458b366d191eed7372e9a680e58231 or one of the other asmjit changes

**Closed as completed** 2022-11-25 04:00 UTC
Labels: bug
