### ISSUE TITLE
"Donkey kong 64" polygon tearing

### ISSUE THREAD

**Issue by twarnercool2** [project64/project64#966] opened 2016-02-02 03:59 UTC
At random points, "Donkey kong 64" models stretch out a little bit.

**Comment by vgturtle127** [comment] 2016-02-02 04:13
@twarnercool2 You should probably provide more information than that. Things like:

* Project64 version
* Plugins and versions
* OS version
* ROM version
* Settings used
* Computer specifications
* Maybe a screenshot or video?

**Comment by Isotarge** [comment] 2016-02-02 04:29
This is likely a duplicate of #791

**Comment by LegendOfDragoon** [comment] 2016-03-09 02:09
@twarnercool2 can you close this? It's a duplicate, as Isotarge mentioned.

**Closed** 2016-03-09 02:46 UTC
