### ISSUE TITLE
States - save oldest / load newest

### ISSUE THREAD

**Issue by nr1995** [project64/project64#2127] opened 2021-10-14 19:01 UTC
Am I just missing something here,
or is there no function for saving state to the oldest slot / the next empty slot,
and then loading the most recently saved state?

Cause I've played with a lot of emulators for a lot of systems,
but I've never had to press “1” then save, then press “2” then save, etc. etc.
while always remembering the last number I pressed in my head.
Is there anything more modern on the horizon?

**Comment by IronYoshi64** [comment] 2021-10-14 23:36
This would be a very nice addition! And you are right, this is not a thing yet, you can only Select a slot, then save and load from that slot, or Save As a state and Load state from. It would be nice if this can be added sometime, since yeah so many other emulators already have this feature.

**Comment by Squall-Leonhart** [comment] 2021-10-16 23:30
lmao, you gen z kids.

**Comment by nr1995** [comment] 2021-10-17 05:39
> lmao, you gen z kids.

I'm in my 30s and have a wife and daughter.
But thanks for letting us know who to come to for useless and patronising.

**Comment by Squall-Leonhart** [comment] 2021-10-18 09:55
use google  to find your way back to retroarch.

**Comment by dftf-stu** [comment] 2022-08-05 16:00
@nr1995: older ticket #1455 is already open to request this, please add a comment there to support it.
(IronYoshi64 already has).

@project64: I'd suggest you could close this as a duplicate of #1455

**Closed as completed** 2022-08-05 23:35 UTC
