### ISSUE TITLE
Supercross 2000 LLE MTC0 error.

### ISSUE THREAD

**Issue by AmbientMalice** [project64/project64#104] opened 2015-02-20 01:20 UTC
Supercross 2000. Interesting game. Runs at 620x480, which I find to be very interesting since "true-ish" 480i resolution is extremely rare.

Anyway, attempting to boot the game in PJ64 in LLE mode results in the following error.

MTC0
CMD_START

In 1964 LLE, this error does not display, but the game freezes upon reaching the main menu. mupen64plus runs it fine.

Thought this might be relevant to the Indiana Jones and the Infernal Machine problems.

**Comment by AmbientMalice** [comment] 2015-02-20 01:59
Error seems to be fixed when running the latest version of PJ64 from the 19th of Feb, unless I use HatCat's LLE RSP.

**Comment by cxd4** [comment] 2015-02-20 02:04
Because DPC_BUFBUSY_REG was set when it shouldn't be.
That's related less to LLE in PJ64, more to cycle-accurate timing.

pj64 rsp ignores it, mine throws the system message you saw that there is a lock hazard on a DPC reg

**Comment by AmbientMalice** [comment] 2015-02-20 03:08
On a slight tangent, is there a particular reason Supercross 2000 is set to Interpreter by default?

**Comment by dsx-** [comment] 2015-02-21 03:44
it isn't

**Comment by cxd4** [comment] 2015-02-25 00:05
Not able to reproduce that error message you mentioned @AmbientMalice.
```
MTC0
CMD_START
```
It's not happening on my end with either the CPU recompiler or interpreter, so I can't tell you whether this is a genuine issue or not within which component--RSP, CPU etc.

Because that error message isn't coming from Project64.  It's coming from my RSP plugin.  So whether it's a RSP issue (most likely on pj64 RSP too not just mine, even though only mine bothers to print an error message about it), a CPU issue/pj64, etc. can't be determined without being able to get that message to happen on here.  So I'm not even sure if this issue is relevant or if it's just something about my RSP plugin you observed.

Also the Indy Jones MTC0 issue is different from the main CPU MTC0...the RSP has an entirely different CP0 of its own than the one the VR4300 has.

**Comment by AmbientMalice** [comment] 2015-02-25 00:32
I figured it out, and I apologise for my stupidity. I was using what seems to be an outdated version of your RSP. The "Iconoclast's RSP" with the LLE\MLE\etc modes. Using build 6 of your RSP has no issues.

**Comment by LegendOfDragoon** [comment] 2015-02-25 00:37
Build 6 is still out dated xD.

**Comment by AmbientMalice** [comment] 2015-02-25 00:40
On another note, I figured out why I thought Supercross 2000 was set to interpeter by default. It's because of this issue - https://github.com/project64/project64/issues/138

The cfg file contains alterations to game settings such as enabling\disabling expansion pack or interpreter\dynarec. It carries over between emulators because it's stored in C:\Users\[Account]\Config\ for some reason. So RDB changes\improvements\whatever end up getting overridded by whatever changes were made in the past. This could be a problem, IMO.

**Comment by project64** [comment] 2015-02-25 00:41
does this happen with default plugins/settings? If not can we close this issue?

**Comment by AmbientMalice** [comment] 2015-02-25 00:43
It doesn't happen with default plugins. Feel free to close.

**Comment by cxd4** [comment] 2015-02-25 00:44
I can't remember what I changed in older RSP to have or not have the "MTC0\nCMD_START" message, but I'm sure it was just something I removed out of instinct since it was really related to tracking atomic DP command buffer writes, cycle-accuracy etc. which is not something I could control anyway.  I don't remember what or why I removed that long ago though.

So yeah, you could click the close button or project64 could do it.

**Closed** 2015-02-25 00:44 UTC
