### ISSUE TITLE
[Bug]: Using load states crashes the emulator

### ISSUE THREAD

**Issue by xiartic** [project64/project64#2219] opened 2022-03-25 20:26 UTC
### Expected behavior?

In "Project64-Dev-4.0.0-5767-d7e732a" load states still worked like they're supposed to but something has broke since "Project64-Dev-4.0.0-5772-a249705" causing the emulator to speed up after loading the save state and hanging up with the message "CN64System::RunRSP() Unknown memory action" or just closing the emulator.

### Actual behavior?

To not crash when trying to use save states.

### Steps to reproduce the problem

1. Use a load state
2. 
3.
4.
5.
...

### Error messages?

![crash](https://user-images.githubusercontent.com/78692485/160195608-9bcfc51f-7394-408f-882c-91e9a8a36b1d.PNG)

### What game were you playing?

Title: Super Mario 64 & Legend of Zelda: Ocarina of Time

Nintendo 64 game or Nintendo 64 Disk Drive: Nintendo 64

ROM information: (File > ROM info, or context menu > ROM information in the ROM
list)

Save type: (Auto detected by the emulator)

Original or modified ROM?:(original US rom)

### Specifications and build details

Project64: (Project64 Dev-4.0.0.5772-a249705)

OS: (Windows 10 21H1):

CPU: Intel Core i5-3350P

RAM: 8 GB

Graphics: Nvidia GTX 1060-3GB

### Using included plugins

- [X] I can confirm I am using the included RSP, audio, input, and graphics plugins

### Plugins used while the issue occurred

Graphics plugin (and HLE or LLE): GlideN64 rev.c8b3f63
Audio plugin: Project64 audio plugin Dev-4.0.0.5722-a249705
Input plugin: Project64 input plugin Dev-4.0.0.5722-a249705
RSP plugin: RSP plugin Dev-4.0.0.5722-a249705

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by DerekTurtleRoe** [comment] 2022-03-26 01:06
@xiartic Have you tried using another RSP plugin?

**Comment by Squall-Leonhart** [comment] 2022-03-26 06:46
save states are not guaranteed compatible bewteen major core changes, that said it seems to be caused by Pj64Audio itself and not replicated with other RSP plugins.

![unknown 1](https://user-images.githubusercontent.com/1098176/160228486-deabbb2f-18a1-41dd-b969-a924c62adb27.png)

**Comment by xiartic** [comment] 2022-03-26 07:10
@DerekTurtleRoe Just tried cxd4's and parallel's RSP plugins giving the same problem. As Squall-Leonheart's saying changing the audio plugin to Jabo's Directsound 1.7.0.7 does work as a workaround. Using Azimer's 0.70 causes the audio to corrupt upon loading a save state temporarily and sometimes crashes just when using PJ64's default.

**Comment by Te-M** [comment] 2022-03-31 08:23
I noticed this too and was only using the latest dev version.  Sometimes changing to HLE audio w/o having a plug-in worked too.  I think every included plug-in I tried would encounter it eventually (or just loading it to a freeze) so it got to that I'd just cycle through them until I got through what I was doing.  Weirdly I even had one that would persist crashing between program restarts that eventually went through for no apparent reason!

**Comment by IronYoshi64** [comment] 2022-03-31 12:19
Dang, sounds like a bad regression. I am still using Project64-Dev-4.0.0-5767-d7e732a as my main, and I know that one doesn't have the issue here. I would recommend general users to revert back to that one until this issue is completely fixed for the time being.

**Comment by RokkumanX** [comment] 2022-05-31 07:41
Just wanted to say and chime in here that I can confirm that I have had the same problems as of 4.0.0-5808

I'm using: 
- ParaLLEl-RDP or angrylion-RDP-Plus for GFX, 
- ParaLLEl-RSP or cxd4 RSP for RSP, 
- Azimers Audio WIP 9 or WIP 10 for Audio,
- NRage Input Plugin solely

Every time I make a save state the emulator crashes when attempting to load the save state and the Reliability Monitor in Windows clearly states that the faulty module is Azimers Audio (also happens with the included PJ64Audio)

HOWEVER, I admit that 4.0.0-5808 is the first "new" version of Project64 I have used in years and the version I have stuck with ON/OFF periodically is 2.4.0-1364 which don't suffer from these save state loading crashes at all.

There is a tremendous gap between 2.4.0-1364 and 4.0.0-5808 and since Project64 isn't my main go to N64 emulator anymore I have no idea when or what commit that broke this.

EDIT:

Oh, so it seems 4.0.0-5767 is fine as other have already stated...*blush*
My bad...

**Comment by project64** [comment] 2022-05-31 13:45
Hopefully this fixes it
https://github.com/project64/project64/commit/fae1de846aa224ac8e5f823a4af33e03e855ac15

when AI_BITRATE_REG was being updated, it would instead change the dac rate, so when saved dac rate would instead have the bitrate, and loading that state would have the wrong values here

**Comment by Squall-Leonhart** [comment] 2022-05-31 14:13
It doesn't.

**Comment by project64** [comment] 2022-05-31 14:31
@Squall-Leonhart did you make a new save or did you try to load an existing save?

**Comment by Squall-Leonhart** [comment] 2022-05-31 14:43
i hard reset.

**Comment by project64** [comment] 2022-06-01 01:54
looking at hard reset hopefully https://github.com/project64/project64/commit/8e5efea6f7679df786227d828b110318be63b860 fixes that issue

**Comment by project64** [comment] 2022-06-01 07:19
can I close this now

**Comment by RokkumanX** [comment] 2022-06-01 10:39
The issue is fixed as far as I can tell, no crashes when loading states anymore.

**Closed as completed** 2022-06-01 11:26 UTC
Labels: bug

**Comment by Marcelo20XX** [comment] 2022-12-18 04:18
Same problem as OP on dev-4.0.0.6028. Crashing when loading newly created savestates on Legacy of Darkness.

**Comment by Squall-Leonhart** [comment] 2022-12-18 06:59
this bug is closed, start a new one.
