### ISSUE TITLE
[Bug]: Banjo Kazooie Game Freezes after hitting Congo the Ape with Kazooie's eggs

### ISSUE THREAD

**Issue by nolesapex** [project64/project64#2302] opened 2022-11-14 00:46 UTC
### Expected behavior?

When you go to Mumbo's Mountain (The first world you reach in the game), there's an ape on a tree that throws Oranges at you. If you shoot eggs at him (after the third hit) the game completely freezes up. Even when having settings at default and switching to different plugins the freezing still persists.

Specs: AMD Ryzen 9 3900x

          6900XT Card

### Actual behavior?

Game completely freezes up and no way around.

### Steps to reproduce the problem

1.Go to congo in Mumbo's mountain
2.Reach the ape standing on the tree
3.get on the wooden platform and shoot eggs at him
4.You have to hit him 3 times to get a Puzzle piece
5.After hitting him the THIRD time is when the game immedietly freezes.
...

### What game were you playing?

Title: Banjo Kazooie

Nintendo 64 game or Nintendo 64 Disk Drive:

ROM information (First you must uncheck "hide advanced settings" in the settings menu, then File > ROM info should show up, post the information contained there in this field. Alternatively, you can right click the ROM in the ROM browser and hit "ROM information".): 
Save type: (attach game save or save state here)

Original or modified ROM?:(attach patch if applicable here)

### Specifications and build details

Project64: Development Version 4.0.0.6013-02660c2

OS: (include version and OS build number using WinVer): Windows 10

CPU:Ryzen 9 3900x

RAM:32 gigs

Graphics:6900XT AMD Card

### Using included plugins

- [X] I can confirm I am using the included RSP, audio, input, and graphics plugins

### Plugins used while the issue occurred

Graphics plugin (and HLE or LLE): Both were used (the default and Jacobs plugin)
Audio plugin:default 
Input plugin:default
RSP plugin:none

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment] 2022-11-14 10:28
A save must be supplied for anything involving a specific reproduction.

This is caused by recompiler optimizations.

**Comment by Squall-Leonhart** [comment] 2022-11-25 03:14
Fixed by https://github.com/project64/project64/commit/e3aa2514c1458b366d191eed7372e9a680e58231 or one of the other asmjit changes

**Closed as completed** 2022-11-25 04:00 UTC
Labels: bug
