### ISSUE TITLE
Re-Volt - Freezes

### ISSUE THREAD

**Issue by Predator82Germany** [project64/project64#361] opened 2015-04-09 15:42 UTC
When I start a race & drive a couple seconds the game freezes
I mean this was sometimes fixed in a version of 1.7
Can anyone remember?

**Comment by cxd4** [comment] 2015-04-09 16:24
dunno not familiar with this game at all, you have a saved state or something?

**Comment by Predator82Germany** [comment] 2015-04-09 16:26
Only start a race

**Comment by Frank-74** [comment] 2015-04-09 20:47
Fixed it with https://github.com/Frank-74/project64/commit/80b60f880969bfd8666c1ab32ea75c71d1662e87

**Comment by AmbientMalice** [comment] 2015-04-09 22:48
@Frank-74 Have you tried everything else before enabling FAT with all the problems that brings? Last time I checked, the game didn't freeze with CF=2 and Jabo's audio.

**Comment by Frank-74** [comment] 2015-04-10 00:04
@AmbientMalice Yes, tried every possible option.  Game freezes here with Jabo and CF=2.  Also after repeated reloading, the save corrupts and the game stops loading totally.  You then have to delete the .mpk to be able to load the rom.

**Comment by AmbientMalice** [comment] 2015-04-10 03:45
In addition to Frank-74's fix, I changed CF to 1, since the game has an ATROCIOUS framerate with CF=2.

**Comment by LegendOfDragoon** [comment] 2015-05-11 19:46
I think this issue can be closed now :smiley:

**Comment by Predator82Germany** [comment] 2015-05-12 06:28
Hadn´t a newer build to test but ...

**Comment by Frank-74** [comment] 2015-05-15 05:42
This is broken again. :(

Freezes now with FAT as well.

**Comment by oddMLan** [comment] 2016-03-15 09:15
Can't reproduce with current version.
I suppose it was fixed with the making of FAT ON and Dynamic AI count global.

@Predator82Germany  please close

**Comment by LegendOfDragoon** [comment] 2016-03-15 09:36
I think Frank is correct, I remember it freezing even with FAT. Should be tested more, before closing.

**Comment by oddMLan** [comment] 2016-03-15 09:47
Tested HLE & LLE GFX, Recompiler & Interpreter RSP and Interpreter & Recompiler.
2+ minutes into the race and no freeze.

**Comment by oddMLan** [comment] 2016-03-16 00:48
@LegendOfDragoon @Frank-74 Were you able to reproduce the bug with the current master?
I don't think @Predator82Germany is around here anymore, last public activity shows May 2015, that's almost a whole year. Maybe this should be closed since I tested like 8 times and couldn't reproduce the bug even with different settings (except if FAT is OFF), but I'll let @LegendOfDragoon @Frank-74 have the last word.

**Comment by cxd4** [comment] 2016-03-16 03:45
Frank's probably inactive too for a few months at a time, when life happens.  Probably will be back.

**Comment by LegendOfDragoon** [comment] 2016-03-16 04:20
I guess it's been too long. Certainly FAT is better suited for this game. For all I know, either something unrelated caused the freezing, or maybe it's fixed for good now. I didn't do as much testing as I previously did, but I just get the feeling I won't be able to reproduce the freeze.

**Comment by oddMLan** [comment] 2016-04-02 22:05
Fixed.
@project64  Close?

**Closed** 2016-04-06 22:21 UTC
