### ISSUE TITLE
[GLideN64][Feature Request] Add support for frame buffer extension API

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#811] opened 2015-12-05 00:50 UTC
https://github.com/gonetz/GLideN64/issues/808

@project64 
Can this be implemented in Project64?

**Comment by project64** [comment] 2015-12-05 01:54
not at the moment, 

I plan to re-write some of the memory handling soonish for android, when that happens it should be

**Comment by vgturtle127** [comment] 2015-12-08 10:14
> for android

Does Project64 work on Android? And if so, does that mean it works on Linux? Even if only basic functionality? Or am I getting my hopes up? :laughing:

**Comment by project64** [comment] 2015-12-08 19:14
@vgturtle127 it does not work for Android. But all my changes lately is so that it will run on android in the future, which is why the project64-core was made so the UI can be windows based but the core will be able to run on other OS's, mac, android, linux, etc. Still a lot more to do tho

**Comment by vgturtle127** [comment] 2015-12-08 20:45
@project64 OK. Glad to hear progress is being made, though. :smile:

**Comment by oddMLan** [comment] 2016-03-15 10:32
Related issues of interest
#72 #574 
This issue kinda could be considered a duplicate of #72, actually thinking about it.

Same goal: Faster frame buffer emulation.
Come on!! It needs to be done to truly take N64 emulation to the next level of efficiency :+1:

**Comment by LegendOfDragoon** [comment] 2017-07-11 16:48
Isn't this a duplicate of 574?

**Comment by project64** [comment] 2017-07-11 23:49
close enough to #574, do not need multiple open issues

**Closed by project64** 2017-07-11 23:49 UTC
