### ISSUE TITLE
Package file was not signed correctly

### ISSUE THREAD

**Issue by Lithium64** [project64/project64#1170] opened 2016-08-14 14:49 UTC
When I try to install on my garbage mt6572 always appears this error "Package file was not signed correctly"

![report](https://cloud.githubusercontent.com/assets/10705488/17649862/07f6c492-6215-11e6-9e66-760fd4b50f85.png)

**Comment by Frank-74** [comment] 2016-08-14 14:57
I get the same on my Versus TouchPad 7.

It works on my Samsung J1 phone.  But my fingers are too big for the mini screen I have on my phone.

**Comment by cxd4** [comment] 2016-08-14 21:52
lol.  just like getting Java applications signed with a security certificate:  very very hard, pointless and yet required

**Comment by vgturtle127** [comment] 2016-08-15 06:06
@Lithium64 @Frank-74 You guys might need to try something newer, it should work on Android 4.4 and up at least.

**Comment by project64** [comment] 2016-08-15 06:20
@Lithium64 is that from google play? Where are you getting the apk from?

**Comment by Lithium64** [comment] 2016-08-15 15:23
@project64 Google play

**Comment by Frank-74** [comment] 2016-08-15 15:24
@project64 
"Package file was not signed correctly" is message from Google Play.
"Application not installed", is message using apk on beta forum, installing with Android package installer.

**Comment by Frank-74** [comment] 2016-08-16 03:01
I've searched for this error, and the solution recommended is to clear the Google Play app cache.  Goto manage apps > all > Google Play > Clear Cache.

However, now I get a new error.

Can't install app

"Project64 - N64 Emulator" can't be installed.  Try again, and if the problem continues, get help troubleshooting. (Error code: -103)

The "get help troubleshooting" link is:
https://support.google.com/googleplay/troubleshooter/6332137?p=fix_download_install&hl=en&rd=1

**Comment by Lithium64** [comment] 2016-08-17 00:44
@Frank-74 I tried this solution and the same thing happened on my phone

**Comment by Frank-74** [comment] 2016-10-03 14:40
Latest version installs fine on my Versus TouchPad 7, Android version 4.0.4.

Though have another problem.  It's not scanning or finding any roms after pointing it to the correct folder and clicking OK.

**Comment by project64** [comment] 2016-10-03 17:56
@Frank-74  go to advanced mode (go to about, click "project64 for android" 6 times, advanced mode enabled should show. 

In advanced/logging/project64 core. Set Path to verbose, and User interface to verbose. This should generate a log in drive/Project64/logs. That should help what is going on there.

**Comment by Frank-74** [comment] 2016-10-03 22:17
@project64 I set Path and User Interface to verbose, exited settings and my rom's now display, without going back to search for new roms.

They never showed up before enabling logging.  I tried restarting a couple of times before, to see if the rom's would show up.  Weird.

They never showed up before enabling logging.

**Comment by project64** [comment] 2016-10-03 22:31
you can try reset and see if it reproduces .. tho reset does not reset everything full yet, just config file at the moment.  now that you can see games in the list, do they run?

**Comment by Frank-74** [comment] 2016-10-03 23:43
Tried reset settings, restart, roms are still showing.

Games I've tried have run ok.  Slow though.  SM64 doesn't get above 27VI's on the Start menu screen, ingame max 38VI's.  Also 'Emulation Started' never goes away, unless I enable speed display.

Ridge Racer has some graphics/geometry problems when cars get close.

Will test out the controller tomorrow, need to find my mini usb adapter.

**Comment by project64** [comment] 2016-10-04 00:16
you might need to point the game dir to a directory that has no games in it and then point it to the real dir to see if that changes anything.

I still need to work on speed more, If you turn on CPU percent and find gfx being a high value, then yes adding small res might speed it up. I can look at that when I get the recompiler doing more and I start to run out of things that I can easily do to speed it up more.

**Comment by Frank-74** [comment] 2016-10-04 03:00
CPU percent flicks between 0-40-48% on start menu.  Leave it to go to demo, and CPU stays at 0.0% during demo.  VI's don't improve even though CPU stays at 0.0%.

**Comment by project64** [comment] 2016-10-04 04:22
strange CPU is 0%

**Comment by project64** [comment] 2016-10-04 21:49
not sure if it will fix it, but there was some issues with cpu monitoring which I fixed in https://github.com/project64/project64/commit/a278a2cde64f97cc93c33a8d4a293fc34d19c7ea

**Comment by Frank-74** [comment] 2016-10-05 00:46
Now, instead of 0.0%.  It does this.
Sorry about the bad pic, took it with my mobile.
https://www.dropbox.com/s/zzj15yf6xtowtyb/20161005_013646-1.jpg?dl=0

**Comment by project64** [comment] 2016-10-05 00:56
that looks like an issue I had before, what version are you running?

**Comment by Frank-74** [comment] 2016-10-05 00:59
Latest from Alpha forum.  v2.3.1-130-ga278a2c.

**Comment by project64** [comment] 2020-04-28 11:30
closing old issue, if this is still an issue it can be reopened

**Closed by project64** 2020-04-28 11:30 UTC
