### ISSUE TITLE
[Request] 16 MB RAM size

### ISSUE THREAD

**Issue by Tarnadas** [project64/project64#1374] opened 2017-09-18 05:15 UTC
The developers from Super Mario 64 Online need it, so I was wondering, if this is possible.
 My C++ and Emulator knowledge is limited, so it would be easiest to just ask.

**Comment by Frank-74** [comment] 2017-09-18 14:41
It's already supported.  But not selectable from the options.  I added the option back in February, but never did a PR for it.  You can see what is needed to change in these commits:
https://github.com/Frank-74/project64/commit/305a2b2db3c81f136643c7d817e46142280b58de
https://github.com/Frank-74/project64/commit/c032d1fd865914f59bf4d7b17feaedce915a8494
https://github.com/Frank-74/project64/commit/63e7c5cb4f6c6b8f2a8e59f943824872c77dbc78

For now, you can add RDRamSize=16777216, under the Super Mario 64 entry in Project64.cfg.

**Comment by Frank-74** [comment] 2017-09-18 15:35
I've just done a PR to add 16MB option.

**Comment by MelonSpeedruns** [comment] 2017-09-18 16:26
Frank, thanks for your help! I've tried injecting custom code int he 16mb area and it works! However, trying to loads 3D models freezes the game... Any idea what could be the cause?

**Comment by Frank-74** [comment] 2017-09-18 17:54
> However, trying to loads 3D models freezes the game... Any idea what could be the cause?

@MelonSpeedruns
Sorry, no idea.  Best uneducated guess is if they're new 3D models, there might be a limit to amount of polygons.  N64 3D models are all very low polygon count.

**Comment by cxd4** [comment] 2017-09-19 05:51
Also a lot of stuff in Project64's RSP (and even some HLE graphics plugins) assume a maximum RDRAM address of 0x7FFFFF which is good for only 8 MB and not 16, so adding the support in Project64's core doesn't fix the plugins.

**Comment by OffSetEyeBrow** [comment] 2018-05-10 22:39
hi, i downloalded the edited file, but is the android edition?

**Comment by project64** [comment] 2018-10-10 21:13
Not going to make it a visible option, closing for now

**Closed by project64** 2018-10-10 21:13 UTC

**Comment by whateverlior** [comment] 2022-11-06 14:52
> Not going to make it a visible option, closing for now

well thats badass
