### ISSUE TITLE
Overhaul default PJ64 sound settings.

### ISSUE THREAD

**Issue by AmbientMalice** [project64/project64#435] opened 2015-05-04 02:52 UTC
@project64 I'm wondering if it would be acceptable for me to make a pull request to enable FAT by default for all games and also set AI=0 as default for all games. (Problematic games can be tweaked later in the RDB.) I've been testing, and this seems to get excellent results for most games. Games like Turok 2 crackle with Jabo using this setting, but sound fine with Azimer's. Resident Evil 2 seems perfect.

**Comment by LegendOfDragoon** [comment] 2015-05-04 03:18
I'd do more testing before doing an overhaul. I understand that disagreements will be inevitable, but this should be planned carefully imo.

>Games like Turok 2 crackle with Jabo using this setting, but sound fine with Azimer's.

The game still crackles, unless you use audio sync. Some games like Super Smash Bros do better with FAT off. However, I'm fine with default AI=0, but might be a hassle for me to disable FAT for every game that is better off disabling FAT. Try enabling the "Show CPU Usage" option and you'll see why it doesn't crackle with Azimer's while crackling with Jabo's.

**Comment by AmbientMalice** [comment] 2015-05-04 03:35
I didn't hear any crackling in Turok 2 with Azimer's with PBO disabled. I was just wandering around the first level, though.

**Comment by LegendOfDragoon** [comment] 2015-05-04 04:16
Hmm, well Turok 2 runs good with Azimer's plugin I guess. I did hear minor crackling with PBO disabled, but not something I'd make a big deal about :) , especially since PBO is enabled by default. I vaguely remember the sound screwing up eventually, but will have to keep testing, just in case I'm getting mixed up on what plugin I tested it with.

Certainly, games like Super Smash Bros, WDC, and Rogue Squadron are better off without FAT enabled. Eh, I guess worst case scenario is that I simply disable FAT by default on my local copy of PJ64 ;/ . I just think that more testing should be done first.

**Comment by AmbientMalice** [comment] 2015-05-04 04:32
I definitely agree more testing is needed. I'm not sure enabling PBO by default is a good idea. It's trading higher CPU usage to eliminate what should be very little crackle. But I guess that's Azimer's territory - and I believe he wants FAT enabled universally. (My understanding is that FAT is not just more accurate, but it's crucial to working netplay. Mind you, I'm not sure whether dynamic FAT would work with netplay.)

Oh, yea, and the DK Rap is synced with FAT/AI=0, which is nice.

**Comment by cxd4** [comment] 2015-05-04 04:48
wtf is pbo


Program Batshit Optimization?

**Comment by AmbientMalice** [comment] 2015-05-04 04:57
@cxd4 PBO=Prevent Buffer Overruns. It's Azimer's audio sync setting.

On a related note, if dynamic FAT is enabled by default, then PJ64's audio sync will have to be disabled. Plus Jabo's audio sync will need to be removed from the RDB for DK64. (Probably for the best, though. FAT on its own seems to give superior results, even for Jabo.)

**Comment by cxd4** [comment] 2015-05-04 05:00
https://www.opengl.org/wiki/Pixel_Buffer_Object

Peanut butter oreos. :)

**Comment by LegendOfDragoon** [comment] 2015-05-04 05:00
>I definitely agree more testing is needed. I'm not sure enabling PBO by default is a good idea. It's trading higher CPU usage to eliminate what should be very little crackle.

Keep in mind that even though the number for r4300i % will be higher, it doesn't actually use more CPU. It's just sleeping, during the time when there's a buffer overrun. So this could make the VI/s drop below 60, in games where FAT is not too good.

>(My understanding is that FAT is not just more accurate, but it's crucial to working netplay. Mind you, I'm not sure whether dynamic FAT would work with netplay.)

Accuracy is implementation defined, but potentially, sure. At  of this current implementation, I wouldn't call it more accurate for all games yet, although for some, sure. The new FAT should work with net play. As long as the results are always deterministic, it should be fine. I know PJ64 1.7's FAT worked good for net play, according to some people.

>Oh, yea, and the DK Rap is synced with FAT/AI=0, which is nice.

It was pretty good, although it messes up near the end for me. Might be because of VI/s dropping in some parts on my end, since I use angrylion's plugin for testing that, because it has better timing for DK rap than HW plugins.

**Comment by AmbientMalice** [comment] 2015-05-05 12:34
Been doing some testing. Overall results positive. DK64 is a bit odd. Azimer's is laggy. Also, occasionally crackly. Not sure what's going on there. However, the odd thing is that I've encounted zero polygon tearing with dynamic FAT. (DK Rap starts to desync around Diddy's segment, unfortunately, however.)

**Comment by Azimer** [comment] 2015-05-05 12:49
It makes me wonder if I should makes Counts Per Byte decimal.  I suppose after thousands of samples it could potentially add up.  I will experiment when I have time but if it doesn't fix DK64, it'll be pointless cpu cycles.

**Comment by Azimer** [comment] 2015-05-05 15:53
Even with the increased precision and modifying the VI Refresh I was unable to make any progress.

**Comment by Frank-74** [comment] 2015-05-05 16:36
Maybe a variable buffer setting would be useful for some games.  While trying to get perfect sync in Perfect Dark's intro, with Fixed Audio and AI=0, changing the VI from 1500 up or down delays the audio even more.

**Comment by AmbientMalice** [comment] 2015-05-06 12:37
I've hit a rather odd snag. Turok 2/3 run well with Azimer's FAT/AI=0 aside from the fact the audio starts crackling after loading a save state. (Regardless of whether the audio reset hack is enabled.) Also, and I could be wrong, the music tempo in Turok 2 feels too fast after loading save states.

This could be related to the weird behavior of Turok titles where the games freeze every other time you load a save state. Also, Turok 2 has no audio with Jabo unless CF=1 or FAT is enabled.

Also worth noting Turok 2 noticably crackles with Jabo with FAT regardless of save states.

**Comment by Azimer** [comment] 2015-05-06 16:39
The pj64 spec really should have incorporated a save state/load state functionality.  It makes it difficult to recover and can leave audio DMAs hanging because that state information is not preserved.  I noticed a similar save state thing with golden eye.

**Comment by LegendOfDragoon** [comment] 2015-05-06 19:21
Funny, I get no audio at all when loading a save state with FAT enabled in Turok 2. Looks like I may need to tweak my workaround for loading save states.

>Also worth noting Turok 2 noticeably crackles with Jabo with FAT regardless of save states.

Likely because of buffer overrun. That's the typical problem I see with FAT. What I don't get is why sometimes for me, Turok 2 crackles with FAT and other times it doesn't.

**Comment by AmbientMalice** [comment] 2015-05-08 04:34
>@Azimer
>The pj64 spec really should have incorporated a save state/load state functionality. It makes it difficult to recover and can leave audio DMAs hanging because that state information is not preserved. I noticed a similar save state thing with golden eye.

Do you think there is any solution? Because currently it seems PJ64 has incorrect audio after loading save states with basically every game if FAT+AI=0 is used. Even if the AudioResetOnLoad hack is used.

**Comment by AmbientMalice** [comment] 2015-05-10 06:18
PJ64 2.x definitely has a problem when it comes to save states with FAT. Azimer's XAudio compensates by slowing down. DSound just crackles instead. In Turok 2's case, disabling Prevent Buffer Overruns causes Turok to play normally for a few seconds before suddenly running too fast.

Interestingly, PJ64 1.7 loads save states just fine with FAT enabled.

**Comment by dsx-** [comment] 2015-05-12 15:40
no crackling here on turok 2 - FAT on, sync using audio off, ai=0, any audio plugin

idk about save states or whatever

**Comment by Frank-74** [comment] 2015-05-12 18:27
AudioResetOnLoad causes the audio to be delayed here.  The cure I found was to either disable AudioResetOnLoad, or go to Options > Settings, and click Ok.  For some reason, the audio then resumes without the delay.  https://github.com/project64/project64/issues/449

**Comment by LegendOfDragoon** [comment] 2015-05-12 18:35
@Frank-74 , AudioResetOnLoad is only used for loading save states. So it has to be something else.

**Comment by Frank-74** [comment] 2015-05-12 18:42
@LegendOfDragoon Try Goldeneye with FAT=0, and enable AudioResetOnLoad.  On changing screens for level selection/mission, audio is delayed by almost a second here.  Opening Options > Settings and clicking Ok (without changing anything), immediately fixes it to instant response.

**Comment by LegendOfDragoon** [comment] 2015-05-12 18:59
@Frank-74 , I think disabling AudioResetOnLoad was just a coincidence. In any case, I will debug PJ64 and set a breakpoint on the AudioResetOnLoad code and see if it ever gets reached.

I suspect the problem is FAT. Just by looking at the results, I can see a problem already. Anyway, instead of opening options menu in Pj64, just try pausing for 1 sec at random times and let me know if you still have a delay.

**Comment by Frank-74** [comment] 2015-05-12 19:11
@LegendOfDragoon Yes, pausing for a split second works as well.  I just clicked outside the PJ64 window and immediately back in the PJ64 window and instant response.  Occasionally it doesn't happen, most times it does.  Sometimes the audio will have a fast stutter instead of a delay.  Only when AudioResetOnLoad=Yes though.

**Comment by Frank-74** [comment] 2015-05-12 19:23
@LegendOfDragoon It only ever happens on the first rom start after starting PJ64.  So open PJ64, start Goldeneye straight away, and 99% of the time you'll either get bad stuttering audio or a delay.  A microsecond of pause fixes it.

**Comment by LegendOfDragoon** [comment] 2015-05-12 19:30
Well, i debugged and the breakpoint was never set.

@Frank-74 , can you do me a favor and temporarily modify your local copy of PJ64. Basically I want you to comment out this line https://github.com/LegendOfDragoon/project64/blob/3d57e37a886a3e2e04ea6aeb7b298052fc45f85a/Source/Project64/N64%20System/N64%20Class.cpp#L1738

and L1739. The idea is to make it unconditional. Then in the RDB, remove AudioResetOnLoad=Yes and let me know if it still happens. The only possible explanation I can think of, is that the RDB code itself is bugged, so I'm trying to narrow it down.

**Comment by Frank-74** [comment] 2015-05-12 19:37
Do a pause after rom load and it will fix the delay.  Maybe its just the loading of RDB settings on first rom load that is slow, because End Emulation and restart works as well.  Though even then, a pause improves the latency from ~30ms to 10ms.  A pause would make it more sturdy.

**Comment by Frank-74** [comment] 2015-05-12 19:47
@LegendOfDragoon Removed the lines and AudioResetOnLoad=Yes and there is still a slight delay.  Though I think now its due to the amount of options read from the RDB.  How about calling pause after RDB settings have loaded?  Might be worse for me because I'm on a PC that's 10 years old.

**Comment by Frank-74** [comment] 2015-05-12 22:32
@LegendOfDragoon There's a problem with Pause (F2) as well.  Keep tapping F2, pause and unpause and the sound will do the same stutter I get on first load ( or else a delay).
Here's a recording of me tapping F2 after resetting Goldeneye.
https://dl.dropboxusercontent.com/u/9498358/n64/pause_problem.mp3
So there is something wrong somewhere.

**Comment by LegendOfDragoon** [comment] 2015-05-13 01:19
@Frank-74 the problem is FAT. That stuff you mention about the RDB intrigues me. To think 1 extra line in the RDB makes that much of a difference for you. Should definitely be looked into.

**Comment by Azimer** [comment] 2015-05-13 03:56
```
Edit: this only happens with Azimer's XAudio2 and FAT=0.
```
If you can't duplicate the result on a different audio plugin, I would point my finger at the audio playback (audio plugin) and the issue opened there.  We need to narrow down what is actually at fault with FAT=0 vs FAT=0 + Azimer's XAudio2.  Is the delay only with XAudio2 also?  I also know you are using Windows XP which has XAudio2 sitting on top of DirectSound.  This may also be an issue.  @Frank-74

**Comment by Frank-74** [comment] 2015-05-13 18:10
@Azimer The distorted stuttering I was getting was my own fault.  I'd changed the sample rate to 48000 and forgot.  No distortion with 44100, but I still get the delay.  And with other plugins too.  So I'm sure its a Project64 fault.  https://github.com/project64/project64/issues/449

**Comment by Frank-74** [comment] 2015-05-20 04:12
@AmbientMalice I suggest something like this for new UI options.  Dynamic option should grey out the AI box to make it uneditable and force 0 value.  Thinking about it, it should have an 'None' option as well.
Mockups.
![newuifat1](https://cloud.githubusercontent.com/assets/11056843/7718869/bfc0c1b6-feae-11e4-872e-061f9c0d0a9b.png)
![newuifat2](https://cloud.githubusercontent.com/assets/11056843/7718870/c149e0d0-feae-11e4-918b-60b9fec98d7e.png)
![newuifat3](https://cloud.githubusercontent.com/assets/11056843/7718871/c26ac2b8-feae-11e4-9405-a782f60a15ca.png)

**Comment by AmbientMalice** [comment] 2015-05-20 04:48
@Frank-74 That seems like a pretty decent idea.

>Thinking about it, it should have a 'None' option as well.
Probably for the best.

Do you think Sync using Audio should be kept or dropped, since Azimer's plugin will likely be handling any audio sync going forward?

**Comment by Frank-74** [comment] 2015-05-20 05:28
>Do you think Sync using Audio should be kept or dropped, since Azimer's plugin will likely be handling any audio sync going forward?
@AmbientMalice Should be kept but overhauled probably, maybe changed to 'Audio plugin sync', 'off' would use the core, 'on' for the audio plugin.

**Comment by AmbientMalice** [comment] 2015-05-20 05:34
>Should be kept but overhauled probably, maybe changed to 'Audio plugin sync', 'off' would use the core, 'on' for the audio plugin.

It should probably also be forced off if using any form of FAT.

**Comment by LegendOfDragoon** [comment] 2015-05-20 07:58
I think the way it already is, is fine. Only thing I'd change if anything is set Sync using Audio to off by default. Even then, I don't mind tweaking the settings myself.

**Comment by AmbientMalice** [comment] 2015-05-20 08:07
@LegendOfDragoon I do think that having a clearly labelled "dynamic" setting is more intuitive for end-users than "0=dynamic".

Sync audio conflicts badly with FAT, so it'll have to be disabled anyway. It could be left in or removed -- that's really Zilmar's call, though.

**Comment by MofoMan2000** [comment] 2015-05-26 04:49
I'm curious as to whether enabling the "Fixed Audio Timing" is the better (read: more accurate) behavior. I know it's pretty important to making CPU output deterministic (being required for netplay) but what the hell does it actually *do*?

**Comment by AmbientMalice** [comment] 2015-05-26 07:31
@MofoMan2000 To quote @death-droid,

>"Fixed audio timing is a fix to a problem in the original PJ64 where results could be completely erratic since audio interrupts were not linked to length of time. So it would never give the exact same results every time you played (terrible for netplay)."

It's a more accurate, less error-prone method for handling audio timing. Using an AI Count Per Byte value of 0 makes it dynamic, which solves the problem of games that change AI values on the fly, leading to crackling/popping -- also, setting values manually for every game is kinda clumsy.

PJ64 used to solve timing problems by syncing to audio via Jabo's plugin, but this is very unreliable and causes timing/performance issues. Also, please note that Jabo/PJ64's audio sync is incompatible with Fixed Audio Timing.

**Comment by oddMLan** [comment] 2016-03-15 09:31
No longer an issue as per the merge of #881 & #882 
please close :)

**Closed** 2016-03-15 09:54 UTC
