### ISSUE TITLE
Castlevania (U) (V1.2) - SP DMA WRITE Error

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#375] opened 2015-04-14 00:49 UTC
Run Castlevania (U) (V1.2) with default settings/plugins, wait for error.

After the demo starts playing I got the error.
SP DMA WRITE
SP_DRAM_ADDR_REG not in RDRam space.

**Comment by Frank-74** [comment] 2015-04-14 00:54
And if the level demo manages to complete without the above error, it will play the intro again and then crash with a fatal error.

**Comment by AmbientMalice** [comment] 2015-04-14 01:30
Unfortunately, I can't replicate the error. I just watched the intro several times on loop.

**Comment by Frank-74** [comment] 2015-04-14 01:36
Hmmm, just ran again, and it never even made it to the demo.  About five seconds after the geezer with a violin and Fatal Error: Stopping emulation, preceeded by a second of noise.

@AmbientMalice Are you using the default settings and plugins?  I'm using a build from yesterday.

**Comment by cxd4** [comment] 2015-04-14 01:42
If you get corrupt audio then that error came probably from the RSP plugin, rather than the core.

Things which could affect it:
a) RSP set to interpreter
b) 8 MB RDRAM
c) HLE audio
d) a different RSP plugin

**Comment by Frank-74** [comment] 2015-04-14 01:45
Using default HLE Gfx, LLE Audio, RSP Recompiler, 8MB RDRAM.

Wonder if its releated to the issue @LegendOfDragoon reported about recompiler and protect memory.
![image2](https://cloud.githubusercontent.com/assets/11056843/7128861/3c1be93c-e250-11e4-8601-a9e1ec0eb825.png)

**Comment by LegendOfDragoon** [comment] 2015-04-14 02:26
I am unable to reproduce this exact issue. However that Protect Memory issue does affect this game.  

You'll know if it's caused by Protect memory, if you get no errors in Cpu Interpreter since Protect memory only affects Cpu recompiler.

**Comment by Frank-74** [comment] 2015-04-14 02:48
I got the SP DMA WRITE error only the first time I ran the game, several times its crashed since then.  But now its about to start the 5th replay and its not crashed yet.  Hmmph..  Its random, random is hard.

**Comment by LegendOfDragoon** [comment] 2015-04-14 02:53
Enabling Fixed Audio Timing should make the results more consistent.

**Comment by Frank-74** [comment] 2015-05-03 19:57
New Fixed Audio with AI=0 makes this issue redundant.  New Fixed Audio doesn't cause any issues with timing anymore.  :+1: 

Close?

**Comment by LegendOfDragoon** [comment] 2015-05-03 19:59
I think it would be too soon to close. I think it's important to track down obscure bugs.

**Comment by cxd4** [comment] 2015-05-17 16:52
If it was just a timing issue then it would make sense to close this now that fixed audio timing fixes it.

**Comment by cxd4** [comment] 2015-05-17 16:54
>Using default HLE Gfx, LLE Audio, RSP Recompiler, 8MB RDRAM. Default settings from RDB.

If there is reason to think that something besides timing is causing it then try seeing if CPU interpreter && RSP interpreter has the issue still when you un-do your fixed audio timing fix.

**Comment by AmbientMalice** [comment] 2015-05-17 22:09
Worth noting that Sim City 64 DD has SP DMA errors without FAT, too.

**Comment by oddMLan** [comment] 2016-03-15 09:25
>If it was just a timing issue then it would make sense to close this now that fixed audio timing fixes it.

Yep. A lot of weird bugs dissapear like magic with FAT and Dynamic AICount.
I think this should be closed.

**Comment by project64** [comment] 2020-04-28 11:07
closing old issue, if this is still an issue it can be reopened

**Closed by project64** 2020-04-28 11:07 UTC
