### ISSUE TITLE
v2.3.2 Release

### ISSUE THREAD

**Issue by project64** [project64/project64#1249] opened 2017-01-19 21:35 UTC
I am looking at releasing v2.3.2 publicly for both android and windows.

I was originally thinking that http://forum.pj64-emu.com/showthread.php?p=68833 was going to be a release candidate.

but I should fix #1245 before release.

Anything else that should be fixed before a release?

**Comment by LegendOfDragoon** [comment] 2017-01-20 00:27
I think double checking these issues might be a good  idea
#1205 #1225 #1190

**Comment by project64** [comment] 2017-01-20 00:55
#1205 I think is fixed
#1225 would like to fix, not sure how as I can not reproduce it to work out why
#1190 I guess I should look at and try to verify if it is a real issue or not

**Comment by project64** [comment] 2017-01-20 01:09
with #1190 I am not sure if I will look to much at it now .. I plan to do a lot of work cleaning up the gfx plugin after the release. Which is one of the main reason I want to do a release now cause once I start to really clean up/refactor the gfx plugin going to be a while before it can be releasable.

**Comment by Frank-74** [comment] 2017-01-20 02:02
Looks good to me, there's a few more issues that can be closed too.  I'm to too drunk to list them now.  It;s my birthday, was 43 today...  Pist as a fart at the moment, but have enough mentality to know that there are quite a few issues that should be closed.

Interested to know if the compressed saves are fixed  with the updated zlib on XP with VS2010+ builds.

**Comment by project64** [comment] 2017-01-20 02:06
Happy birthday. Well it works for VS2008 so it is OK for now. Will look at getting the builds to be VS2015 post this release so will need to fix it after then.

**Comment by LegendOfDragoon** [comment] 2017-01-20 02:08
I guess it's fine to release then.

**Comment by project64** [comment] 2017-01-20 02:11
I need to fix the manifest, will do that maybe tomorrow then do a build and look at releasing that build

**Comment by Frank-74** [comment] 2017-01-20 02:14
@project64 Thanks, it already worked fine on VS2008.  The problem is it doesn't work on VS2010+ for XP users.  If VS2008 is to be dropped this needs to be fixed first.

VS2010+builds means XP users cannot use compressed savestates at the moment.  Big problem if VS2008 is to be dropped.

**Comment by project64** [comment] 2017-01-20 02:26
It needs to be worked out before VS2008 is dropped

**Comment by JunielKatarn** [comment] 2017-01-20 02:30
@Frank-74 @project64 I'll work on that and let you know.

On an unrelated note, VS2017 will e released this year, and it builds Pj64 fine (and also runs fine in post-XP Windows versions).

**Comment by LegendOfDragoon** [comment] 2017-01-20 02:45
>On an unrelated note, VS2017 will e released this year, and it builds Pj64 fine (and also runs fine in post-XP Windows versions).

Is it worth using 2017 instead of 2015, or should I wait longer? I've been waiting for 2017 to come out, before installing Visual Studios on my desktop. Can't have too much bloat on my SSD.

**Comment by Frank-74** [comment] 2017-01-20 02:52
You've got to be kidding......  It took 7 hours to install VS2015 last week....  Bullshit, and bollocks to VS2017, i'm not going through that install again........

**Comment by cxd4** [comment] 2017-01-20 02:58
Just keep upgrading Visual Studio until you run out of hard disk space on your Windows partition, then you won't have to use it anymore.

**Comment by project64** [comment] 2017-01-20 03:08
part of the reason I do not try to change the target version of VS is a pain to install and such .. not so bad it is free now, but when it was also payed I really wanted to stay with the version I had the license for. 

Have to go to min VS2015 for angle so I will probably be staying with that version for a long time. Also good to wait till the first one or two service packs are out.

**Comment by Frank-74** [comment] 2017-01-20 04:05
#1205, #921 and #667 are fixed I'm sure...

**Comment by oddMLan** [comment] 2017-01-20 05:23
The manifest thing should definitely get sorted out, hopefully without needing to recur to create one in the source; I think the best solution is just to let Visual Studio generate it during compilation time. I think that IS possible on Visual Studio 6 and above, but couldn't figure out how to modify the VS2008 solution to set up that flag.

Also I think #1027 and #653 are good candidates that should get fixed and shouldn't be too hard to squash.

**Comment by Frank-74** [comment] 2017-01-20 05:32
@oddMLan Isn't #653 fixed now?  Everything gets unbolded when set to it's default setting after clicking apply for me now.

**Comment by Fanatic-64** [comment] 2017-01-20 10:12
@Frank-74 The plugin drop-down menus on the Plugins tab don't get unbolded when selecting the default plugins for me, using a build of the latest source.

May I suggest merging #1246 ? I have tested it as much as possible, if there are any edge cases (which I doubt) they will be found by more general use.

**Comment by JunielKatarn** [comment] 2017-01-20 10:59
> Is it worth using 2017 instead of 2015, or should I wait longer? I've been waiting for 2017 to come out, before installing Visual Studios on my desktop. Can't have too much bloat on my SSD.

@LegendOfDragoon It's not worth it having both. Any of them is good enough.
Personally, I'd pick 2017 (once it's officially released), because the installation is way more modular you can get everything you need for Project64 under 7GB (quite less than earlier versions). Plus, lates features and bugfixes.

**Comment by oddMLan** [comment] 2017-01-20 16:24
Yeah, I think Project64 should pick the lastest available version if it's gonna stick with that version for the years to come.

**Comment by LegendOfDragoon** [comment] 2017-01-20 19:57
I guess I'll wait for 2017 to officially release. Anyone know when that will happen?

**Comment by project64** [comment] 2017-01-20 22:48
> Yeah, I think Project64 should pick the lastest available version if it's gonna stick with that version for the years to come.

I like the lastest stable version if I was going to choose not the bleeding edge. I have yet to see a version of visual studio which has not needed a service pack.

I think I will stay with VS2015 ..

**Comment by oddMLan** [comment] 2017-01-21 00:34
2015 is such a burden to install though :weary: 
But yeah I guess that sounds reasonable enough

**Comment by cxd4** [comment] 2017-01-21 03:50
Each next version is a greater pain to install than the previous.

**Comment by project64** [comment] 2017-01-22 09:19
ok another release candidates http://forum.pj64-emu.com/showthread.php?p=68845#post68845

anything else that needs to be done

**Comment by oddMLan** [comment] 2017-01-22 16:26
Gonna test it as soon as I get home.

**Comment by oddMLan** [comment] 2017-01-23 03:03
> @oddMLan Isn't #653 fixed now? Everything gets unbolded when set to the default setting after clicking apply for me now.

Almost, but
1) go to the main config panel
2) switch the video plugin to something else and click apply
3) switch back to the default plugin (Jabo D3D9 1.7)

the plugin settings dont get unbolded even when changed back to the default. everything else yes


also  #1027  isn't fixed with the latest commits. games like Conker, Diddy Kong Racing etc don't use the mempak (well DKR only when saving ghost data) but those games are creating a dummy memory pak with no data, I assume just formatted. It would be best if the emu checked if the mempak is just formated with no meaningful data so keep it in RAM and only flush it to disk when bytes have been written to it.
from what I gathered from the code it seems to be doing that but it's not working right as of now

**Comment by project64** [comment] 2017-01-23 03:52
the values that project64 has for blank is:
https://github.com/project64/project64/blob/master/Source/Project64-core/N64System/Mips/Mempak.cpp#L78

if it changes any one of these then it will create the file. I had a look at kazooie when I was first testing the changes and it would change some of those values.  

So maybe something in the initialize values are wrong.

**Comment by oddMLan** [comment] 2017-01-23 03:57
![imagen](https://cloud.githubusercontent.com/assets/7278372/22191120/44dc6854-e0e5-11e6-84ec-9d3d313b16c7.png)


I compared the beginnings and the only thing that differs is that 0x71 that shows later on

**Comment by project64** [comment] 2017-01-23 05:08
maybe the mem pak init code in pj64 is wrong and it should be 0x71

**Comment by project64** [comment] 2017-01-23 05:09
with #653 it just needs strings to compared with the default easy enough to fix.

**Comment by project64** [comment] 2017-01-23 05:54
I suspect the defaults of https://github.com/project64/project64/issues/1027 is not correct which is why we are getting saves, but I have tweaked the mem pak code probably to much already this close to the release. I think this will have to be fixed in the next release.

**Comment by project64** [comment] 2017-01-23 05:56
I am doing a build of the current source. I think I will try to release that if it seems to compile fine.

**Comment by wfowler1** [comment] 2017-01-23 12:16
Wasn't 2.3.2 released in early October? At least, the source code of the project at some point was tagged as being the code for 2.3.2. This seems like it would need another version bump.

**Comment by project64** [comment] 2017-01-23 12:23
I released a 2.3.1 .. well at least for android and created a 2.3.2 tag .. cause the building used the tag to get the name .. I need to move the tag to the correct one ..

I probaly should not get the version number from the tag which means I do not have to tag it till the next version. Which I planned to make better from now

**Comment by Frank-74** [comment] 2017-01-23 16:09
Re mempak default values.

Looking at the blank mempaks created.
From 0x300 up to 0x500 the pattern written is this.
00 00 00 00 00 00 00 00 00 03 00 00 00 03 00 03
00 03 00 03 00 03 00 03 00 03 00 03 00 03 00 03

From 0x500, the repeating pattern is 00 03 until the end.

**Comment by cxd4** [comment] 2017-01-25 23:12
It's supposed to vary IIRC.

I studied the mempak format thoroughly back in 2012 but can't remember what that address is for.  The Git repository for it is off-line from my GitHub; I'd have to dig it up elsewhere to find what values should be written there.

**Closed** 2019-02-03 19:35 UTC
