### ISSUE TITLE
Knife Edge - Nose Gunner speed issues.

### ISSUE THREAD

**Issue by AmbientMalice** [project64/project64#284] opened 2015-03-17 11:43 UTC
This is sort of a formality, since this game plays wrong on every single emulator I've ever encountered. Basically, once the player takes control, the game races through the level at breakneck speed. Since no amount of tweaking comes even close to fixing it, I'm thinking the game has timing behavior unlike any other N64 title.

**Comment by LegendOfDragoon** [comment] 2015-03-17 18:37
Good find, I can confirm this is an issue on every emulator I've tested.

**Comment by cxd4** [comment] 2015-03-18 18:01
>game plays wrong on every single emulator I've ever encountered. Basically, once the player takes control, the game races through the level at breakneck speed.

https://github.com/project64/project64/issues/32 Probably related

**Comment by Frank-74** [comment] 2015-05-10 10:51
Seems to play ok now.  Using Fixed Audio on, AI=0, Sync using audio off, latest Azimer's XA2 0.7 WIP 5.

**Comment by AmbientMalice** [comment] 2015-05-10 11:13
@Frank-74 I just tested, and it's still running way too fast. Here's a review with some real N64 footage to compare. https://www.youtube.com/watch?v=kvcR2ao3-28

**Comment by Frank-74** [comment] 2015-05-10 11:26
@AmbientMalice I see now.

**Comment by LegendOfDragoon** [comment] 2015-12-30 21:22
For some reason, running the game at 60 fps is too fast. I guess it wasn't meant to / able to play at 60 fps, yet there is no cap to prevent it from running at 60. I'll try and see if I can dig deeper.

**Comment by oddMLan** [comment] 2016-03-15 08:17
>For some reason, running the game at 60 fps is too fast. I guess it wasn't meant to / able to play at 60 fps, yet there is no cap to prevent it from running at 60. I'll try and see if I can dig deeper.

If this theory is true, setting `ScreenHertz` to an appropriate value (< 60) would effectively fix the game running too fast.

**Comment by LegendOfDragoon** [comment] 2016-03-15 08:25
I think the most practical approach would be to come up with a gameshark code. Maybe @retrobenny could help with that. Once the game code has been studied, it could help lead towards a proper fix.

The issue with messing with stuff like VI refresh or CF is the fact that it affects the whole game. I think I'll try experimenting with VI refresh though. I think underclocking helped on 1964, iirc.

**Comment by Frank-74** [comment] 2016-08-28 05:17
If a function could be added to limit the DL/s.  This game runs correct speed at 20 DL/s.
ScreenHertz=20 is correct speed ingame, locks VI and DL to 20, but it gets very jerky/unresponsive/slow in places where the game locks the DL's to 20 itself, like the cut scenes before a mission.  It also messes up the audio timing.

Need 60 VI/s and 20 DL/s speed limiter.

**Comment by Tasosgemah** [comment] 2018-05-29 23:36
After so long the game still has the same speed issue in both PJ64 and Mupen

**Comment by theboy181** [comment] 2018-05-30 00:49
You need to cheat at this game! 

Knife Edge - Nose Gunner (U)
FPS Fix

811978D0 0000
811978D2 0000

Note: WIP, makes the game run at 20 fps making it playable. Menus are still too fast probably need to be 30fps to match the N64.

**Comment by loganmc10** [comment] 2018-05-30 01:04
@theboy181 can you explain what that code is doing? It may help us discover a proper fix for this game

**Comment by theboy181** [comment] 2018-05-30 01:09
@loganmc10 It locks the DL's to 20 in game. There is a portion of the game that is locked to 20 VI before the levels start, so I NOP the branch so it doesn't leave it up to the emulator. 

I think the game might look better running at 30FPS and would make the intro's/menus play at the correct rate.

I have a theroy that the real HW is somehow locked at 30FPS and its a default unless specified by the SW. 
I'm most likely wrong though, as I usually am when it comes to these type of things. I used a similar hack for Duck Dodgers to get the cut scenes to run at 30fps. This game seems to be locked at 30 on the real HW despite the SW's involvement.

**Comment by project64** [comment] 2020-04-28 11:05
closing old issue, if this is still an issue it can be reopened

**Closed by project64** 2020-04-28 11:05 UTC

**Comment by haydenmc** [comment] 2022-01-16 02:26
This still reproduces today with 3.0.1.

@theboy181 your patch works perfectly up until the rescue cinematic in the Dead City level, after which the game appears to soft-lock.

I did a little bit of digging around in the debugger myself to see if I could find a way around this, but I'm _very_ new to this space and didn't make too much progress.

**Comment by Frank-74** [comment] 2023-07-07 00:39
Can't get this game to boot at all in latest Dev 4.

Wanted to test this code by @theboy181 

Knife Edge - Nose Gunner (U)
FPS Fix (30fps hack)

D012AABB 0000
800E0BDF 0003
D012AABB 0001
800E0BDF 0000

Note: Counter Factor = 1 , Fixed Audio Timing = On
Makes the game run at its proper FPS
