### ISSUE TITLE
RDB updates

### ISSUE THREAD

**Issue by vgturtle127** [project64/project64#847] opened 2015-12-23 05:36 UTC
So I have some ROMs that need to be added to the RDB, and I also have some corrections and additions and stuff. What is the best way for me to do this? What is the minimum amount of data I need to add something to the database? The RDB info.txt file and stuff is pretty useful, but it doesn't explain what info is *needed* for Project64 to recognize the ROM, etc etc.

Basically, I want you guys to tell me how you like your RDB entries to look so I don't cause a bunch of problems or anything. :blush: 

Anyway, I can start with a list of the ROMs and some info I have gathered from them, but there are quite a lot, so if I can get away with just adding them to the RDB, that would be great. :smiley: 

I saw @AmbientMalice recently added something to the RDB, so I have a basic template for one of the new things I want to add:

[766309EA-3F64A369-C:45] <This is from the Perfect Dark MP3 mod, how is this calculated?
MD5=86D5516CD22CFFE9FEC42FE1A61408FE
CRC1=0xE4C44FDA
CRC2=0x98532F4A
16.0 Megabit ROM
Good Name=Analogue Test Utility V1.00 by WT_Riker (POM '99) (PD).z64
Internal Name=Analogue Test Utility V1.00 by WT_Riker (Is this format alright?)
Status=Compatible
Core Note=
Plugin Note=
RDRAM Size=8
Save Type=

What else do I need?

Any feedback or assistance would be much appreciated. :smile: :+1:

**Comment by SigmaVirus** [comment] 2015-12-30 10:52
What you need depends on which roms/games were talking about here.
Some roms/games needs more stuff then others as shown in the examples below:

[ABA51D09-C668BAD9-C:58]
Good Name=40 Winks (E) (M3) (Beta)
Internal Name=40 WINKS
Status=Compatible
Plugin Note=[video] errors:menus, actors during cutscenes black; use Force Alpha Blending
RDRAM Size=8

[C2E9AA9A-475D70AA-C:45]
Good Name=Banjo-Tooie (U)
Internal Name=BANJO TOOIE
Status=Compatible
Core Note=(see GameFAQ)
Plugin Note=[video] (see GameFAQ)
AiCountPerBytes=625
Culling=1
Save Type=16kbit Eeprom
Self Texture=1
RDRAM Size=8

I suggest you try your games and see what kind of options you need to add.

**Comment by AmbientMalice** [comment] 2015-12-30 11:28
Entries should be alphabetical for actual settings, but not "Name" and "Status" stuff. So, for example, RDRAM should go before Self Texture. But in my humble view, the Jabo video settings like Self Texture should be stripped from the RDB because they're stupidly bloated and the plugin needs to go as soon as possible.

The current RDB is a complete mess with a lot of inconsistent ordering and far too much bloat.

**Comment by SigmaVirus** [comment] 2015-12-30 14:49
I'm probably gonna get hanged for this but my RDB only contain entries for the 11 games that I actually own, the rest of the entries I have simply deleted.

Perfect order, no clutter, no bloat and way easier to maintain.

**Comment by project64** [comment] 2015-12-30 19:40
I do have a program in the source code (SortRdb) to sort he rdb to make it more accurate and clean it up, it is a manual process to run it.

**Comment by vgturtle127** [comment] 2015-12-31 05:01
@SigmaVirus Thanks for the examples. I already know pretty much most of the RDB entries that I want to edit or update, mostly public domain ROMs and demos and stuff. A few commercial games though.

@AmbientMalice OK, so alphabetic other than the names and status. Are there any other Jabo-only entries you can think of?

@SigmaVirus :laughing: That actually makes a lot of sense. I'd build my own RDB from scratch if I thought anything would run. :smiley: 

@project64 Can it be compiled with GCC/MinGW/Cygwin? If not, could you give me a binary so I can test it out while I am editing the RDB?

Also, what do you think about @AmbientMalice 's idea about removing Jabo-only RDB stuff?

**Comment by AmbientMalice** [comment] 2015-12-31 07:08
>Also, what do you think about @AmbientMalice's idea about removing Jabo-only RDB stuff?

For the record, removing those entries is essentially cutting ties with the Jabo video plugin completely. The plugin will behave even worse than it already does. I'd like this to happen, but it can't be a half-measure.

**Comment by vgturtle127** [comment] 2015-12-31 08:43
@AmbientMalice Just a few specific entries, though, right? I mean how many games used Jabo-specific entries?

**Comment by SigmaVirus** [comment] 2015-12-31 09:14
@vgturtle127

Building your own RDB from scratch is actually quite easy and doesn't even require Visual Studio at all, just Notepad.

And I have done it many times before, one for Project64 1.6, one for Project64 1.7 and one for Project64 2.2

As I said earlier I only own 11 games and they are among the popular ones so it's quite easy to maintain this self made RDB.

I usually check for RDB updates to see if the games I own have gotten changes.

**Comment by vgturtle127** [comment] 2016-01-02 02:04
@SigmaVirus I know, I use Notepad++. However, I own most of the N64 games one way or another, so maintaining my RDB would be just as much of a chore as the one that comes with Project64. :smile:

**Comment by SigmaVirus** [comment] 2016-01-02 14:47
Must be pretty tough maintaining both your N64 collection and your RDB?

I'm pretty neatpicky when it come to games so while I got a few, I only got the most essential ones.

**Comment by vgturtle127** [comment] 2016-01-02 16:55
@SigmaVirus Yeah. :smile: 

Also, that includes all the public domain ROMs and a bunch of stuff designed for flash carts and backup systems and such. Most of the stuff I have isn't even in the RDB yet. Hopefully, that will change soon. Some of the stuff works pretty good all things considered.

**Comment by oddMLan** [comment] 2016-03-15 10:36
Kind of a duplicate of #31

**Closed** 2016-03-16 00:08 UTC
