### ISSUE TITLE
PJ64 FAT basically broken on RE2.

### ISSUE THREAD

**Issue by AmbientMalice** [project64/project64#1270] opened 2017-02-03 02:53 UTC
PJ64's audio is currently kinda okay for most games, but Resident Evil 2 is a stuttering mess with FAT enabled. And of course FAT is required for  the game's speech to work.

**Comment by LegendOfDragoon** [comment] 2017-02-03 02:56
Is this only with Jabo's plugin? I noticed musyx games are bad with Jabo's audio.

**Comment by AmbientMalice** [comment] 2017-02-03 09:37
>Is this only with Jabo's plugin? I noticed musyx games are bad with Jabo's audio.

I think so. And it probably affects other games, too. :( PJ64 needs a replacement audio plugin as soon as possible.

**Comment by Frank-74** [comment] 2017-02-04 17:33
It seems to be a regression in register caching.  It affects other Musyx games like TWINE too.  Turn off register caching and audio doesn't stutter.

**Comment by LegendOfDragoon** [comment] 2017-02-04 17:53
>It seems to be a regression in register caching.

I don't think so, because it happens on interpreter and I know that turning off register caching often makes it buggier than leaving it on.

>PJ64 needs a replacement audio plugin as soon as possible.

Agreed. Not only are MusyX games problematic, but so are others like Boss Studios.

**Comment by Frank-74** [comment] 2017-02-04 18:10
@LegendOfDragoon You mentioned in #1125 that you know what commit caused this problem.  Can you remember which commit it was?

**Comment by LegendOfDragoon** [comment] 2017-02-04 19:49
@Frank-74 it's #984 iirc. The problem is, I've tried comparing the old code with that code (in-game) and the results of the equation were never different. The problem has to be something else. It only affects Jabo's, so I highly doubt it's a core issue.

It's not worth the time to try and fix issues with closed source plugins imho. It's far more productive to improve open source plugins at this point.

**Comment by Frank-74** [comment] 2017-02-04 23:06
It affects Azimer's XA2 as well.  I get clicks and pops in RE2.

I reverted #984 and now my Azimer's XA2 has no clicks and pops with FAT and sync options turned off in Azimer's.

**Comment by oddMLan** [comment] 2017-02-05 03:47
I had noticed some popping on certain games with FAT on recently (subtle but noticeable) whereas it didn't happen before, now I know why. Any clue on why that commit breaks FAT?

**Comment by LegendOfDragoon** [comment] 2017-02-05 04:31
>It affects Azimer's XA2 as well. I get clicks and pops in RE2.

I heard no difference on my end.

>I had noticed some popping on certain games with FAT on recently

What plugin and what games? Did you try a build of PJ64 from a year ago to compare?

>Any clue on why that commit breaks FAT?

Most likely a bug in Jabo's audio plugin. That commit shouldn't have any negative affect on audio.

**Comment by Frank-74** [comment] 2017-02-05 16:43
I found another instance of that code in N64Class here:
https://github.com/project64/project64/blob/master/Source/Project64-core/N64System/N64Class.cpp#L1913-L1917
```cpp
    //Fix Random Register
    while ((int)m_Reg.RANDOM_REGISTER < (int)m_Reg.WIRED_REGISTER)
    {
        m_Reg.RANDOM_REGISTER += 32 - m_Reg.WIRED_REGISTER;
}
```

Maybe that is the problem?

**Comment by Frank-74** [comment] 2017-02-05 18:56
Wired always equals 0?

I put in this writetrace, and it never writes.
```cpp
		while ((int)g_Reg->RANDOM_REGISTER < (int)g_Reg->WIRED_REGISTER)
		{
			g_Reg->RANDOM_REGISTER += 32 - g_Reg->WIRED_REGISTER;
			if (g_Reg->WIRED_REGISTER > 0)
			{
				WriteTrace(TraceN64System, TraceDebug, "g_Reg->RANDOM_REGISTER = %X", g_Reg->RANDOM_REGISTER);
				WriteTrace(TraceN64System, TraceDebug, "g_Reg->WIRED_REGISTER = %X", g_Reg->WIRED_REGISTER);
			}
		}
```

**Comment by LegendOfDragoon** [comment] 2017-02-05 19:11
>Wired always equals 0?

In most games, yes. That's one of the reasons why I optimized that code. When wired = 0, doing `random &= 31` gives the same results as looping `random += 32;` . Somehow changing the algorithm, causes Jabo's audio to become really bad in MusyX games with FAT enabled. Makes no sense.

**Comment by cxd4** [comment] 2017-02-05 19:20
Of course, in that same pull request, I had pointed out regressions where changing the algorithm had different results incorrect with the original, but zilmar went ahead and merged it anyway because YOLO don't cause rpgmaster to learn how to efficiently manage multiple branches.

**Comment by theboy181** [comment] 2017-02-05 19:28
asshat never starts regressions! only stops progressions!

**Comment by cxd4** [comment] 2017-02-05 20:55
u mad tho...

**Comment by oddMLan** [comment] 2017-02-05 21:10
>What plugin and what games? Did you try a build of PJ64 from a year ago to compare?

Just from memory.
The games I tried were Super Mario 64 and Banjo Kazooie with Jabo's Audio. The popping is very ocassional though. But before it was perfect. It could very well be a problem with Jabo's Audio, but @Frank-74 confirms there's popping with Azimer's with certain settings where it was none before. Also @cxd4 did point out some differences in the algorithm in the original commit, so the evidence seems to point out, there's something that the commit is doing differently than the original algorithm that shouldn't be.

**Comment by LegendOfDragoon** [comment] 2017-02-05 21:50
>The popping is very ocassional though. But before it was perfect.

That honestly doesn't sound abnormal. Crackling can happen randomly, for several reasons. I don't think it's reliable to simply compare based on a previous experience, when it comes to testing audio. I can watch an intro once and hear no crackling, then try watching again and hear a few crackles. I strongly suggest trying these older builds to see if you can currently hear a difference.

>@Frank-74 confirms there's popping with Azimer's with certain settings where it was none before. Also @cxd4 did point out some differences in the algorithm in the original commit, so the evidence seems to point out, there's something that the commit is doing differently than the original algorithm that shouldn't be.

I don't consider that to be sufficient evidence. That particular commit i referenced, did not even introduce the regression cxd4 was referring to. Regardless, the games with the noticeable audio issues do not set WIRED_REGISTER to a value greater than 31.

>I put in this writetrace, and it never writes.

What game were you testing this with?

**Comment by Frank-74** [comment] 2017-02-05 22:00
@LegendOfDragoon 
> What game were you testing this with?

TWINE and RE2.

Using an if instead of while loop, RANDOM_REGISTER kept decreasing.

**Comment by cxd4** [comment] 2017-02-05 23:15
@oddMLan Yeah, the PR had regressions, but I doubt they're related to the AI.

No one really bothered to fix them, whether they pop up any noticeable changes or not.  They should have been coded properly to begin with though, instead of waiting for zilmar to bypass it and merge it anyway knowing how much he depends on RPGMaster's dynarec improvements to the point where he'll knowingly merge bugged code if it means not chasing him away from submitting more recompiler PRs.

**Comment by cxd4** [comment] 2017-02-05 23:18
>That particular commit i referenced, did not even introduce the regression cxd4 was referring to.

I said, "in that same pull request", not "in that same commit".

**Comment by Frank-74** [comment] 2017-02-05 23:49
There is a problem with the if  (wired==0) else statement.
```cpp
        if (random < wired)
        {
            if (wired == 0)
            {
                random &= 31;
            }
            else
            {
                uint32_t increment = 32 - wired;
                random += ((wired - random + increment - 1) / increment) * increment;
            }
        }
g_Reg->RANDOM_REGISTER = random;
```
RE2 and TWINE, wired always is 0.  So the else statement doesn't happen.

I've changed it to this, and stuttering is gone.
```cpp
	int32_t wired;
        g_Reg->RANDOM_REGISTER -= TimeTaken / g_System->CountPerOp();
        wired = g_Reg->WIRED_REGISTER;
        while ((int)g_Reg->RANDOM_REGISTER < wired)
        {
            if (wired == 0)
            {
                g_Reg->RANDOM_REGISTER += 32;
            }
            else
            {
                g_Reg->RANDOM_REGISTER += 32 - wired;
            }
        }
```
When using variable random, and updating RANDOM_REGISTER after the calc, there are still some minor stutters.

**Comment by theboy181** [comment] 2017-02-06 00:32
Could some is this issue be that PJ doesn't have very accurate timing. I know video plugins suffer from this issue.

**Comment by LegendOfDragoon** [comment] 2017-02-06 01:03
>When using variable random, and updating RANDOM_REGISTER after the calc, there are still some minor stutters.

That only means that the real issue is unrelated to the changes. I noticed this too on my end today. I did some more testing to see which part of the code change triggers the problem. Somehow simply using a local variable for holding the value of RANDOM_REGISTER triggers it.

It's really too bad Jabo's plugin is closed source. It's going to be very difficult to track down the real issue.

>Could some is this issue be that PJ doesn't have very accurate timing.

I believe the issue is most likely Jabo's plugin. Maybe a small chance that there's some other issue in the core.

**Comment by Azimer** [comment] 2017-02-06 04:25
It may be related to the high bits.  The lower 5 bits (0x1f mask) are all that matters.  In Random, the upper 27 are set to 0.  I don't see where in PJ64 those bits are truncated before returning it during MFC0.  Perhaps it makes a difference for the game.

**Comment by Frank-74** [comment] 2017-02-06 04:50
@Azimer 
Apparently the R4300i manual states it's the lower 6 bits that can be non zero for Random and Wired regs.
cxd4 explains here: https://github.com/project64/project64/pull/984#issuecomment-180861540

That would mean a 0x3f mask.

Confused...

It masks in InterpreterOps line 2232:
    g_TLB->WriteEntry(g_Reg->RANDOM_REGISTER & 0x1F, true);
X86RecompilerOps line 7784:
    MoveVariableToX86reg(&g_Reg->RANDOM_REGISTER, "RANDOM_REGISTER", x86_ECX);
    AndConstToX86Reg(x86_ECX, 0x1F);
    Push(x86_ECX);

**Comment by cxd4** [comment] 2017-02-06 05:08
Yeah, generally the RCP virtual registers are all masked, at least before any reads.

I wasn't really paying attention to that though.  That may or may not have been one of the two/three "regressions" I'd commented on with RPGMaster's pull request, but I only really remember one of them and it isn't that one.  If I read through the PR again I might find more than just the one I recall, but tl;dr and I don't really care.

I also wasn't trying to bring up the past as far as comparing regressions to any audio issues now.  I'd tend to doubt they're related; it's just that I have this strange habit of forgetting things that just don't make sense. :)

**Comment by AmbientMalice** [comment] 2017-02-08 04:00
It's pretty unfortunate that such bad audio regressions have crept in and gone largely... I don't want to say "unnoticed", but rather "unexamined" for so long.

**Comment by LegendOfDragoon** [comment] 2017-02-08 04:12
>I don't want to say "unnoticed", but rather "unexamined" for so long.

Can't examine closed source plugins without going through huge hurdles. #1125 and #228 and this issue are all caused by the same issue.

**Comment by project64** [comment] 2017-02-08 05:16
unfortunately I do not help here .. I basically am always running with sound off for a variety of reasons .. so not something I am going to notice .. 

How useful would it be to create a really basic audio plugin that really is just playing the audio buffers with nothing really extra.

**Comment by oddMLan** [comment] 2017-02-08 05:32
@theboy181 @cxd4 @LegendOfDragoon Guys, Emoji Movie is coming out soon 2017 🙃

**Comment by AmbientMalice** [comment] 2017-02-08 05:35
Azimer's plugin is gradually creeping closer to being good enough to replace Jabo's with. IMO, it probably should have been replaced a long time ago and the issues resolved as a consequence instead of limping along with Jabo's.

**Comment by LegendOfDragoon** [comment] 2017-02-08 05:41
>How useful would it be to create a really basic audio plugin that really is just playing the audio buffers with nothing really extra.

If you implement adjustable buffers + sync audio option, then it will already be better than a good amount of plugins :smile: . I still use an audio plugin that's based on Basic Audio & 1964 Audio. Plugins based on your audio plugin, work especially well in Boss Studios games, although on the other hand it needs some work for MusyX. 

Anyway I can help, if you decide to make a new audio plugin.

>Azimer's plugin is gradually creeping closer to being good enough to replace Jabo's with.

Agreed, especially since save states now work in the XA2 version.

**Comment by project64** [comment] 2017-02-08 06:30
> If you implement adjustable buffer size + sync audio option

I believe sync audio should be in the core not in the audio plugin ...

What I was thinking was taking the audio plugin I am using for android and just switch out the audio playback with one more suitable for windows (DSound, wave, something like that)

**Comment by LegendOfDragoon** [comment] 2017-02-08 06:44
>I believe sync audio should be in the core not in the audio plugin ...

I think that would only be effective if Fixed Audio Timing is enabled. I guess audio sync isn't really necessary with FAT disabled, since it already can sound great w/o audio sync enabled. So leaving it to the core is fine.

>What I was thinking was taking the audio plugin I am using for android and just switch out the audio playback with one more suitable for windows (DSound, wave, something like that)

I see. Sounds like a good idea. I'd start with DSound and then maybe some day add other APIs like WASAPI. I've been wanting to try WASAPI, to see if I can get better audio in MusyX games. I haven't gotten around to doing that yet, since I feel that having a fast graphics plugin is more important.

**Comment by weinerschnitzel** [comment] 2017-02-09 13:33
Doesn't Bsmiles work on mupen64plus' SDL audio plugin accomplish the same thing minus being SDL instead of DSound?

**Comment by dq6** [comment] 2017-02-11 02:03
Hello everybody!

I've just tested Resident Evil 2 with Project64 2.3.2.202 and both versions I have, run perfect ('perfect' within the limitations of emulation nowadays).

ROMS:
-Resident Evil 2 (U) (V1.1)
-Resident Evil 2 (E)

Plugins:
-Glide64 For PJ64: 2.1.2.202
-Jabo's DirectSound 1.7.0.7
-N-Rage For PJ64: 2.5.2.202
-RSP Plugin 1.7.3.202

Settings:
Everything default **EXCEPT** that I had to change '**Sync using audio**' to ACTIVATED to eliminate stuttering. Same thing occurs with _007 - The World Is Not Enough_, where you need to activate 'Sync using audio' to obtain near-perfect sound, music and speech and avoid stuttering (By the way, Surround is awesome in that game with the above plugins and settings!).

So... I didn't touch anything except '**Sync using audio**' and the games run flawlessly... Of course '**Fixed audio timing**' was active all the time in both versions...

Best regards.

**Comment by theboy181** [comment] 2017-02-12 00:02
![capture](https://cloud.githubusercontent.com/assets/9299743/22858456/f9df9af4-f072-11e6-8b2b-abcfdc2b032f.PNG)
Adding screenhertz=61 and the settings in capture above works too.. However with this setting you get much smoother video as a bonus. 

I have been finding that PJ has some really bad timing issues that need to get sorted.

In the following video you will see how the shadows blink incorrectly because of this issue. This will have an effect on audio where timing is critical. Possibly causing what would appear to be random noise artifact.

https://www.youtube.com/watch?v=NNJo_U8hc4A

**Comment by AmbientMalice** [comment] 2017-02-12 03:04
@dq6 Running FAT and sync audio together makes games run at the wrong speed. It doesn't fix the problem.

**Comment by cascardian** [comment] 2017-02-22 17:38
Echoing this older issue https://github.com/Azimer/AziAudio/issues/144: If the audio plugin is to become nothing more than a buffer playback system, why not integrate it into the core completely, eliminating the plugin interface for that? Otherwise, what purpose would it still serve?

You could also just integrate a well-tested API library like libsndio or PortAudio (PCSX2 uses it) to handle modern OS-specific playback for you (WASAPI, PulseAudio, OpenSL, whatever). That would save you a ton of work and maybe open up the possibility of more easily implementing something like timestretching (Citra, PCSX2, Dolphin) or dynamic rate adjustment (RetroArch) or merely just integrating the framerate limiter later on.

For that matter, is audio HLE actually still needed for anything performance-wise? Why not eliminate that option as well, at least on Windows? It'd cut down on issues you have to deal with.

I'm sorry, by the way; this discussion is perhaps better suited for another issue.

**Comment by LegendOfDragoon** [comment] 2017-02-22 19:04
>For that matter, is audio HLE actually still needed for anything performance-wise?

For desktops, the RSP recompiler is generally fast enough to the point where HLE is usually not necessary. HLE is still useful for very low end hardware, or Android.

**Comment by Frank-74** [comment] 2017-03-17 00:48
Body Harvest is a stutter fest with FAT enabled too.  Also Monaco Grand Prix is worse with FAT enabled.

**Comment by loganmc10** [comment] 2017-05-25 16:08
If you guys need an idea of what it should sound like in a working emulator :stuck_out_tongue: 

https://github.com/mupen64plus/mupen64plus-core/pull/290

**Comment by LegendOfDragoon** [comment] 2017-05-29 17:39
>If you guys need an idea of what it should sound like in a working emulator

How does Twine sound? What about Top Gear Rally as well?

**Comment by loganmc10** [comment] 2017-05-29 17:54
> How does Twine sound? What about Top Gear Rally as well?

They both sound the same in mupen64plus and PJ64 to me, is there a specific issue you know of?

**Comment by loganmc10** [comment] 2017-05-29 17:56
Up until very recently, mupen64plus had issues with the engine sounds in Top Gear Rally, but that was fixed literally this week (https://github.com/mupen64plus/mupen64plus-core/pull/289), and now it sounds the exact same as PJ64 to me, maybe TWINE had issues stemming from the same source.

**Comment by Frank-74** [comment] 2017-05-29 18:12
@loganmc10 The Twisted Edge hack has problems.  I noticed that only one sound can play at any one time.  When the speech plays, the ski's sound on the snow stops.

**Comment by loganmc10** [comment] 2017-05-29 18:21
> @loganmc10 The Twisted Edge hack has problems. I noticed that only one sound can play at any one time. When the speech plays, the ski's sound on the snow stops.

Yeah it's not perfect. On mupen64plus I get an earful of static every now and then as well. I haven't noticed that in PJ64, I'm not sure if that is something that Project64-core or Azimer's Audio has fixed. All Boss games have terrible audio on both emulators. If you lookup World Driver Championship on YouTube and watch some gameplay footage you'll realize pretty quickly that it sounds nothing like the emulators. It's almost like the background music is slightly out of order or something.

**Comment by Frank-74** [comment] 2017-05-29 18:38
> On mupen64plus I get an earful of static every now and then as well. I haven't noticed that in PJ64.

The static happens in PJ64 as well, when the audio has drifted out of time.  It gradually gets worse as audio/video lose sync.

**Comment by LegendOfDragoon** [comment] 2017-05-29 19:18
How often does the static happen? I don't recall hearing that, but it's been a while since I tested Twisted Edge.

>They both sound the same in mupen64plus and PJ64 to me, is there a specific issue you know of?

Well for me, I have to use a very fast video plugin (like Rice Video) to even get remotely decent audio in PJ64 for Top Gear Rally. There's this issue where the audio occasionally goes bad and crackles a lot. In order to make it go away, I have to either keep pausing and unpausing the emulator a few times, or disable frame limiter for a second or two.

For Twine, the voices don't always sound good, from what I remember.

I was hoping that some of these problematic games sound good on at least 1 emulator, but oh well. At least it seems that Mupen64Plus is finally making some progress :smile: . I'll have to try out M64p sometime, to try out a few games.

**Comment by loganmc10** [comment] 2017-05-29 20:49
> How often does the static happen?

on mupen64plus, roughly once a race I would say, I haven't experienced it in PJ64.

@Frank-74 when you refer to "The Twisted Edge hack", do you mean the gameshark code? Or the hack in Azimer's Audio plugin?

**Comment by Frank-74** [comment] 2017-05-30 00:02
@loganmc10 I think the gameshark code was studied what happened, and then the hack was made from it.  So I don't think there's much of a difference as to the function of either.

When testing Twisted Edge, I start the ROM and leave it cycling through the demo's.  After the second demo, it's WAY out of time and then I get intermittent white noise, like when you switch a TV station to an untuned channel.  For about a second at a time.

**Comment by LegendOfDragoon** [comment] 2017-05-30 01:24
I just tested Twisted Edge again and heard what seems to be minor static, after beating a level. Wish i had more time to investigate how this game works.

**Comment by project64** [comment] 2020-04-28 11:55
closing old issue, if this is still an issue it can be reopened

**Closed by project64** 2020-04-28 11:55 UTC
