### ISSUE TITLE
Software Depth Buffer Rendering causes crash. (Glide64)

### ISSUE THREAD

**Issue by AmbientMalice** [project64/project64#283] opened 2015-03-17 11:38 UTC
![untitled](https://cloud.githubusercontent.com/assets/10704701/6686484/cbef1610-cced-11e4-8b25-c30380c9aa75.png)

I came across this while trying to fix Star Wars Ep 1 Racer's lens flares rendering through objects. Many games seem affected - with either freezes or crashes when trying to enable software depth buffer.

**Comment by cxd4** [comment] 2015-03-17 15:38
Exactly how would I reproduce it?  I know I was playing _Resident Evil 2_ with your software depth buffer rendering RDB change to test the depth fix in that game but never saw any freezing or crashing, so how could I get it to crash?

And have you tried running from the debug build of the dll?

**Comment by AmbientMalice** [comment] 2015-03-17 22:09
RE2 doesn't crash with SDB enabled. I'll test with debug later, but the crash is easy to reproduce - just run Ep I Racing with SDB enabled.

**Comment by AmbientMalice** [comment] 2015-03-17 22:45
Game seems to run fine with debug dll.

**Comment by cxd4** [comment] 2015-03-18 18:23
okay sorry took me a while to check, had a headache yesterday.

I turned on "Software Depth Buffer Rendering" in Glide64 2.0.0.4 (latest source compiled from GitHub on here) in Release mode, but could not get the game to crash.  Also tried reloading the ROM and booting it with the option turned on, try to go in-game that never crashes either.

You possibly have a driver crash.  I know z64gl is loaded with those in its OpenGL threading.  Though you say with the Debug build of the plugin there is no crash, but none of my GL error messages pop up for you either (or maybe debugging needs enabling within pj64 itself for different type of error).

As for the "RunRSP" in your error message screenshot, that's really just a generic thing.  It would have probably been a more helpful error message to see the module that is crashing the emulation from the primitive "Project64 has encountered a problem and needs to close" error message rather than those C++ exceptions in this particular case.

**Comment by AmbientMalice** [comment] 2015-03-19 09:46
@cxd4 The problem doesn't affect PJ64 2.1's Glide64 2.0.0.1 plugin, by the way. So this is arguably a regression. What did you use to build PJ64? I used Visual Studio 2013.

Here's my Glide64 dll file. https://www.sendspace.com/file/x48wj5

**Comment by cxd4** [comment] 2015-03-21 02:02
Sorry that it took me so long to check.

I downloaded your PJ64Glide64.dll but still can't seem to reproduce the problem with "Software depth buffer rendering" checked in the advanced settings for Star Wars EP1 Racer (U).  Maybe this is a GL implementation & driver issue on your end and that is why the debug build doesn't have the problem for you.

I alternate between VS2008 and VS2013 out of random situation, but typically I use VS2008 for RAM.

If you suppose this must be a regression, then you can try executing `git checkout #######`, where ####### is the commit number off the GitHub website for each change to PJ64 Glide64, then hit Ctrl+Shift+B to re-build the plugin in Visual Studio.  This way you can test PJ64 Glide64 older commit by older commit until the crashing no longer happens, if that helps you isolate this possible "regression" you suppose.  But I cannot seem to reproduce any crashing on my hardware with your DLL.

It is interesting that you don't have the crashing with my debug build and GL checking code in place, though.  Maybe you should try Mesa3D temporarily (warning this is extremely slow and you should undo this experiment when finished I think):
https://dl.dropboxusercontent.com/u/16494013/mesa_w32.zip

If you extract the OPENGL32.DLL from that zip to the main EXE folder of your installation of Project64, it should cause PJGlide64 to operate off this open-source OpenGL implementation rather than Microsoft's driver for it.  Again since it comes with no accelerator this will make emulation slow but, hopefully give you a new thing to test to see if it still crashes whether it's a fault in your video card drivers, your build settings etc.

**Comment by cxd4** [comment] 2015-03-21 02:05
If you're not confident with using Git terminal commands to test older versions of PJ64 Glide64 I guess I can try to put together an archive of older builds of the plugin by commit.

**Comment by AmbientMalice** [comment] 2015-03-21 02:10
I know how to use git. So no worries there. Out of curiosity, is your GPU and AMD or Nvidia one? Mine is an Nvidia GTX 750Ti. I have some other PCs, one of which is an AMD. I'll test it on them. It's very curious how Resident Evil 2 works fine, but other games don't.

**Comment by cxd4** [comment] 2015-03-21 02:58
`GL_RENDERER:  GeForce 6150 LE/integrated/SSE2`

My other GPU is a GeForce 8??? something, can't remember.

**Comment by AmbientMalice** [comment] 2015-03-21 12:42
Tested using Mesa OpenGL. Still crashed.

**Comment by cxd4** [comment] 2015-03-21 15:26
Better to uninstall that dll then to restore the acceleration and such.

It's probably something on the CPU side with how later versions of the plugin got changed like you said.
Here's a list of all commits on here from under the Glide64 folder:
https://github.com/project64/project64/commits/master/Source/Glide64

**Comment by Frank-74** [comment] 2015-03-21 20:03
Not sure if this matters or is relevant.  But, I had the same error when I built Glide using compiler optimizations.  They seem to break it on my PC.  Other bits of Glide seem broken when compared to Glide64 Final.  For example the GoldenEye bond portrait in Glide for PJ64 is split in 2 with a line down the middle.  Its fine in Glide Final.

**Comment by project64** [comment] 2015-03-21 20:19
I have no idea what is the cause, but it sounds like it could be something like an uninitialized variable or something that is not really clear, so when compiled with different compilers, or setting it changes the code behavior.

**Comment by cxd4** [comment] 2015-03-21 20:50
Though this wouldn't explain why his DLL he uploaded to me has the crash on his system but not mine.

**Comment by AmbientMalice** [comment] 2015-03-21 23:03
Software Depth Buffer uses the CPU to calculate depth, does it not? In that case, perhaps this is a CPU-specific problem and completely unrelated to GPU. I need to test on my other PCs. My main PC is running an Intel Core Quad 9400.

**Comment by LegendOfDragoon** [comment] 2015-03-21 23:51
Rofl I got that run error too.

**Comment by cxd4** [comment] 2015-03-22 00:09
>Software Depth Buffer uses the CPU to calculate depth, does it not?

Depth is all a third dimension to the drawing matrix; whatever is done to calculate the coordinates, the rendering cannot be done using pure CPU ops alone.  So it probably involves both.

**Comment by cxd4** [comment] 2015-03-22 00:15
A shame these plugins can't be tested outside of such a restricted plugin environment. :)

To confirm sanity in my tests Ambient, you might also try the latest PJGlide64 source I just built:
https://dl.dropboxusercontent.com/u/16494013/PJ64Glide64.dll

**Comment by LegendOfDragoon** [comment] 2015-03-22 00:37
>A shame these plugins can't be tested outside of this restricted plugin environment. :)
To confirm sanity in my tests Ambient, you might also try the latest PJGlide64 source I just now built:

Was this in Debug or Release mode? Because it didn't crash for me on the build you just posted, with software depth buffer rendering enabled.

**Comment by cxd4** [comment] 2015-03-22 01:13
It would say if it was a debug build.

**Comment by cxd4** [comment] 2015-03-22 01:42
Forget it.
project64 was right, later in the ROM it crashes if I build with VS2013, but not VS2008.

So actually it is undefined behavior in this Cpisspiss code.

**Comment by cxd4** [comment] 2015-03-22 03:04
I really wish there was a way to keep testing this in VS2008.
It seems just re-building changes in 2013 is enough to make me have to pull the plug for every single thing I check.

**Comment by AmbientMalice** [comment] 2015-03-22 04:49
@cxd4 The Glide64 dll you provided doesn't crash for me.

**Comment by cxd4** [comment] 2015-03-22 16:22
Sort of good then.  It was no regression; the earlier build you tested where it worked had to have been published in the form of a VS2008 build.

I wonder just how many of these Glide64 "regressions" since Gonetz' official release are caused by using VS2008 or something later than the compilers he was using?  Dunno if anyone knows what compiler.

**Comment by Frank-74** [comment] 2015-03-22 17:13
Gonetz used VS2005 for Glide Final according to the .sln in the source.
https://code.google.com/p/glidehqplusglitch64/source/browse/trunk/Glide64.sln

**Comment by LegendOfDragoon** [comment] 2015-03-22 20:08
Well the Glide64final I downloaded used MSVC2008. This is what I see "Microsoft Visual C++ 8.0 DLL Method2".

**Comment by cxd4** [comment] 2015-03-22 21:47
8.0 is 2005 dude.

**Comment by LegendOfDragoon** [comment] 2015-03-22 22:19
Wow the numbers are confusing! You're right xD. The one you linked is 9.0 ;/ .

**Comment by cxd4** [comment] 2015-03-23 00:58
OMG OMG OMG guys you'll never guess what!

On today's computer, I can actually test project64 in VS2013, without having to pull the plug every time!
Isn't that nice? :)

**Comment by cxd4** [comment] 2015-03-23 01:33
```c
static void DepthBuffer(VERTEX * vtx, int n)
{
  if (fb_depth_render_enabled && !(settings.hacks&hack_RE2) && dzdx && (rdp.flags & ZBUF_UPDATE))
```
Now that is an interesting clue.

The setting flag itself is referenced tons of places, but if I'm not mistaken AmbientMalice said that _Resident Evil 2_, in particular, is what doesn't crash with this setting enabled.

**Comment by AmbientMalice** [comment] 2015-03-23 01:57
>I wonder just how many of these Glide64 "regressions" since Gonetz' official release are caused by using VS2008 or something later than the compilers he was using?

Quite possibly. Although I think quite a few stem from incorrect RDB settings. There are a few hacks not accessable from the plugin settings that were used for certain games - to fix seams on textures, for example. I'm gonna check the PJ64 Glide64 rdb later to see whether anything can be improved.

>The setting flag itself is referenced tons of places, but if I'm not mistaken AmbientMalice said that Resident Evil 2, in particular, is what doesn't crash with this setting enabled.

As far as I know, RE2 is the only game that doesn't presently crash with SDBR enabled. I'd have to check the rdb to be sure, though.

**Comment by AmbientMalice** [comment] 2015-03-23 04:04
It appears that Glide64 Final's default settings are entirely different to Glide64 PJ64's. Final had a list of defaults in the Glide64.ini file. Interestingly, Software Depth Buffer Rendering was enabled by default for all games.

**Comment by cxd4** [comment] 2015-03-23 05:27
k test https://github.com/cxd4/project64/commit/f82699c37814b5d2bbfc6f412c4c1103f441bdf0

**Comment by cxd4** [comment] 2015-03-23 05:30
It was an integer segmentation issue with the naked x86 operations on the divide operators.

In the `Rasterize` function's call to `LeftSection`'s call to `idiv16`, which should not have needed asm.

Yeah, RE2 has a per-ROM hack embedded to the plugin and/or settings, which is why this particular function of the depth buffer emulation was never accessed, hence no crashing.

**Comment by AmbientMalice** [comment] 2015-03-23 05:47
@cxd4 I'm adding default values for Glide64 to its RDB file, since it currently lacks them. I'm wondering whether software depth buffer rendering should be enabled by default for all games, as it seemingly was for Glide64 Final. This carries a mild CPU performance hit, but any decent PC should handle it fine, and it'll have the benefit of squashing any possible depth bugs. It's not like per-frame framebuffer which fixes issues at the price of agonising performance overheads.

Any thoughts?

Oh, and great work on the bug fix.

**Comment by cxd4** [comment] 2015-03-23 06:02
Honestly, I didn't know that it was enabled by default for all games.  I never was really familiar with Glide64 that much and never used the plugin much; I just thought of "Software depth buffer rendering" as like one of the last-ever additions/settings they put into Glide64 before its discontinuation.  I know it was needed to get effects like the microcode lighting and blending working in _Bomberman 64_ and the Z-buffer issues in _Resident Evil 2_ but am not really familiar of where it is an improvement with most games in general.

Someone with more history of actually using this plugin would probably have a better answer.

**Comment by cxd4** [comment] 2015-03-24 15:44
Software depth buffer seems as good as the old builds, or we have some issue left in this issue?

**Comment by AmbientMalice** [comment] 2015-03-24 20:46
Seems to be all good now. Closed.

**Closed** 2015-03-24 20:46 UTC
