### ISSUE TITLE
[PJ64-Audio] Getting wrongly locked to 50 VI/s (weird initialization issue)

### ISSUE THREAD

**Issue by oddMLan** [project64/project64#1472] opened 2018-07-03 19:07 UTC
Fresh install. PJ64 v2.4.0-692-g f20dca3
This only seems to occur while using GLideN64 OR PJ64Video. For some reason, Jabo's D3D is not affected. OpenGL issue, perhaps?

Steps
----------------------------------------------------------

- After setting the language. Set GFX plugin to either GLideN64, or PJ64Video. Then set ROM dir and close emu.
- Open any (U) ROM.
- VI/s will be below 60 VI/s and around 50 VI/s. If you disable the frame limit (F4), you'll see the VI/s actually go above 60.

Workaround
----------------------------------------------------------

- Open Project64.
- Open Settings (Ctrl-T) and click OK without making any changes (or close the window).
- Open any (U) ROM.
- VI/s will be correct.

_NOTE: If you disable FAT or Sync-to-Audio, VI/s will show 60 VI/s but the audio is still lagging behind (heavy crackling). If you do the workaround steps before, audio will play correctly._

I don't know if this is a recent bug that was introduced or if it's just this setup that's having issues.

**Specs below**
Processor: Intel Celeron J3060
OS: Windows 8.1
Audio: Realtek ALC235 HD Audio
Video: Intel Braswell IGP (DirectX 11.1 & OpenGL 4.4)

**Comment by oddMLan** [comment] 2018-11-28 20:32
This bug is still actual. I could reproduce with 3 different computers, all using Windows 10.
Can provide screen capture footage if necessary.

**Comment by Frank-74** [comment] 2018-11-28 21:45
I just reproduced it too, by following your steps exactly.

Though I found another workaround that fixes it.

After setting the language.   Open Jabo graphics config, set windowed resolution to 800x600 which resizes the ROM window as well.  Then set GFX plugin to either GLideN64, or PJ64Video. Then set ROM dir and close emu.  Open any (U) Rom and it's perfect...

This is weird...

**Comment by Frank-74** [comment] 2018-11-28 22:56
@oddMLan @project64 
For some reason this weird slow fps issue happens only when changing the default GFX plugin.
Per game plugin settings work ok.

**Comment by Frank-74** [comment] 2018-11-29 00:01
Found the problem.  It IS in Project64-Audio.  It's AI Update.  I just commented out the code and no more problems.
```cpp
EXPORT void CALL AiUpdate(int32_t Wait)
{
    WriteTrace(TraceAudioInterface, TraceDebug, "Start (Wait: %s)", Wait ? "true" : "false");
 /*   if (g_SoundDriver)
    {
        g_SoundDriver->AI_Update(Wait != 0);
    }
    else
    {
        pjutil::Sleep(1); // TODO:  Fixme -- Ai Update appears to be problematic
    }*/
    WriteTrace(TraceAudioInterface, TraceDebug, "Done");
}
```

**Comment by cxd4** [comment] 2018-11-29 03:00
Yeah never delete AiUpdate from audio plugins.  It's optional in the specs but always effs one thing up or another if you remove it.

wb Frank

**Comment by Frank-74** [comment] 2018-11-29 03:15
Well I wouldn't do a PR to remove it.  Removing it shows where the problem is though.
Why having a DirectX GFX plugin as default, and changing to OpenGL GFX as per game plugin works is a mystery though.   And why open/closing settings fixes it as well.

**Comment by cxd4** [comment] 2018-11-29 03:34
Probably not because `int32_t Wait` domain to the function could be the input based on video clock feedback from the CPU and/or graphics plugin.

**Comment by theboy181** [comment] 2018-11-29 15:43
Was this recently introduced, or a problem for a while?

**Comment by Frank-74** [comment] 2018-11-29 16:35
Maybe something to do with the Initialize function in https://github.com/project64/project64/blob/master/Source/Project64-core/Plugins/AudioPlugin.cpp

With the AIUpdate commented out as above, the CAudioPlugin::AudioThread maxes the CPU.
Making no changes the CAudioPlugin::AudioThread uses no CPU cycles whatsover.

**Comment by Frank-74** [comment] 2018-11-29 18:34
@oddMLan Here's another try.  It fixes the problem but does it max out your CPU?
I get between 30% and 44% CPU useage with this.
https://www.dropbox.com/s/znjmqz494x4bk4y/Project64-Audio_noDSsleep.zip?dl=1

**Comment by oddMLan** [comment] 2018-11-29 21:16
Current master with workaround CPU usage:
![e2](https://user-images.githubusercontent.com/7278372/49252408-39571680-f3e1-11e8-9999-7eb44cddd2ac.png)

Your latest build:
![e1](https://user-images.githubusercontent.com/7278372/49252418-3c520700-f3e1-11e8-9de8-d3532a7781fb.png)

Not only the CPU usage is still high, but I still get decreased FPS if I don't open the settings panel first.

**Comment by oddMLan** [comment] 2018-11-29 21:23
@theboy181 Ever since @project64 made the switch to Project64-Audio, a poor man's version of Azimer's Audio, which had always worked without issues for me. 
Azimer's WIP10 has many substantial improvements including WASAPI-Exclusive mode for incredibly low latencies. Honestly I feel the switch to Project64-Audio has generated more problems than it solved, I wish you had gone the road of collaborating with Azimer for Project64's Audio side of things, but since he closed the source to his plugin, it's a little too late now isn't it?

**Comment by oddMLan** [comment] 2018-11-29 21:32
You're right, it's not WASAPI-Exclusive, just regular WASAPI. My bad. I got mixed up with Dolphin, which does have a WASAPI-Exclusive mode.

**Comment by Frank-74** [comment] 2018-11-29 21:56
The problem at least has been identified.  CPU useage for Project64-Audio almost doubles after opening/closing settings dialog.  Which fixes the slow fps.  This is what needs fixing still.

I tried my best.  Removed all thread priority increases and settings.  Increased Audio's CPU useage.  I don't have decreased fps, using PJ64-Video as default plugin.  Just the massive increase in the audio CPU useage after CTRL+T > Esc.  Project64-Audio uses more CPU cycles than Project64.exe after CTRL+T > Esc.

**Comment by theboy181** [comment] 2018-11-30 04:19
59.94 Is the exact hz on a real TV.. Whats is the complaint? Heavy CPU?  If the CPU is hit hard you will get audio cracking.. 

From what I understand is if a game RUNS at 30fps your computer better handle running the game at 60FPS+ when you turn off the framelimit, and if they game runs at 60fps, then you need 120fps+ for they audio to not SUX! 

Can you report if your CPU can handle the audio requirements, meaning 20=60 and 60=120?  I hear loads of people complaining about audio, or maybe I'm just def. 

@LegendOfDragoon has more info about AUDIO and toasters.

**Comment by LegendOfDragoon** [comment] 2018-11-30 16:47
Weird that I can't seem to reproduce the issue. Anyway, what happened to the sliders in PJ64 Audio? That was one of the things I liked about it :disappointed: . I do get inconsistent fps with that sync audio option, but I'm not stuck at 50. I was never a fan of the option and never use it during normal gameplay. Seems like fixed audio timing still has issues.

**Comment by Frank-74** [comment] 2018-11-30 20:44
> Anyway, what happened to the sliders in PJ64 Audio?
@LegendOfDragoon I came up with a buffer calc that gives crackle free audio, and accurate audio/video sync for just about every game.  I tested 144 games, both (U) and (E) regions.  So the sliders weren't needed anymore.  There's only 1 game that needed a different buffer setting, Body Harvest (U).  So probably even the FPS buffer option can be removed and have it apply automatically for that 1 game.  I did a LOT of work on the plugin before I got sick a while back.  Better now.
```cpp
            int32_t BufferSize = 0; double audio_clock = 0; double framerate = 0;
            if (g_settings->FPSBuffer() == true)
            {
                framerate = 59.94004;
                if (SystemType == SYSTEM_PAL) { framerate = 50; }
            }
            else
            {
                framerate = 64;                // Needed for Body Harvest (U)
                if (SystemType == SYSTEM_PAL) { framerate = 53.33333; }
            }
            if (g_settings->TinyBuffer() == true)
            {
                audio_clock = ((video_clock / framerate) * 2);
            }
            else
            {
                audio_clock = ((video_clock / framerate) * 4);
            }
            BufferSize = (int32_t)audio_clock / (g_Dacrate) + 1 & ~0x1;
            g_SoundDriver->AI_SetFrequency(Frequency, BufferSize);
```

**Comment by LegendOfDragoon** [comment] 2018-11-30 23:41
Since this audio plugin is only for PJ64, I'd strongly recommend getting rid of AI_update completely from the plugin.  It's redundant if the audio plugin itself creates another thread. Out of the big 3 zilmar spec emulators, AI_Update is only required on Mupen64.

>I came up with a buffer calc that gives crackle free audio, and accurate audio/video sync for just about every game. 

I guess audio works differently on different hardware because I still get crackling on my old laptop. I think having the option to tweak settings would be good, just in case :smile: . Relatively speaking, the audio plugin is still good. It's just that I'd need to tweak it on my end to fix the crackling in some cases.

**Comment by Frank-74** [comment] 2018-12-01 00:29
I wanted to get the VI/s on the fly, and auto adjust the buffer size to fit.  It would stop crackles even if VI/s went below 59.94.

**Comment by project64** [comment] 2018-12-01 10:37
I have been trying to replicate this and have not succeeded yet it be able to produce it. I wonder if it is some how driver related.

**Comment by Frank-74** [comment] 2018-12-01 13:16
@project64 Can you put up an experiment branch so I can play with it?

I thought something like this should work.
int32_t BufferSize = 0; double audio_clock = 0; double framerate = GetVI/sValue();
audio_clock = ((video_clock / framerate) * 2);
BufferSize = (int32_t)audio_clock / (g_Dacrate) + 1 & ~0x1;

**Comment by Frank-74** [comment] 2018-12-01 17:42
> I'd strongly recommend getting rid of AI_update completely from the plugin.

@LegendOfDragoon I removed it totally from audio plugin, and also from Project64.  I can't detect any difference here.  It doesn't max the CPU with it totally gone.  So not sure why it's there, as you said.
I also removed the HLE Graphics setting from new default options because it was buggy, and added overclock to defaults, used list box for overclock settings instead of edit box, 1x-8x.
https://www.dropbox.com/s/u7dq0xv6wo0idln/Project64-noAIUpdate.zip?dl=1

**Comment by theboy181** [comment] 2018-12-01 17:54
I just noticed something with audio in MK3 and LLE (AL+) and CF=2 

The Audio has more CRACKLE in it with a CF of 2.

**Comment by theboy181** [comment] 2018-12-01 18:14
I followed along with the OP instructions using the latest DEVELOPMENT BUILD (v2.4.0-722-gad19a6f)
* Fresh directory of PJ64
* Set Video Plugin to Project64 Video
* Set Default ROM directory
* Quit PJ64, then reopened it 
* Selected a (U) ROM

PJ will not show anything on the screen - it just hangs on opening the ROM -

There is defiantly something going on here.  


OS Name	Microsoft Windows 10 Pro
Version	10.0.17763 Build 17763

**Comment by LegendOfDragoon** [comment] 2018-12-01 18:42
>@LegendOfDragoon I removed it totally from audio plugin, and also from Project64. I can't detect any difference here

Is the issue fixed after removing AI_Update? Also don't remove it from pj64. Removing it from the plugin should suffice. Other audio plugins like jabo's uses AI_Update, and I think it's better to let the user have more choices for audio plugins. Having it enabled in PJ64 won't affect plugins that don't support AI_Update, because PJ64 will only create the AI_Update thread, if the audio plugin supports it.

**Comment by LegendOfDragoon** [comment] 2018-12-01 21:35
Iirc, Frank uses Windows 8. Maybe this is a Windows 8-only issue? Seems like only @Frank-74 and @oddMLan has the issue.

**Comment by Frank-74** [comment] 2018-12-01 22:11
> turning off sync to audio makes the VI Jump up like there is no frame limit. Tested with BANJO TOOIE

@theboy181 Restart the ROM after turning sync using audio off.  It will lock to 60 VI/s on startup.  The option needs a restart or load F5 savestate.

**Comment by LegendOfDragoon** [comment] 2018-12-01 22:36
Lol for me, Donkey Kong 64 is totally broken. I wonder if my config is causing a conflict with these recent builds. Does this issue occur in other games?

> Probably something funky with Intel GFX and GL.

Possibly. For my old laptop, i get black screen just for restarting or switching games with most OGL plugins. That's why I just prefer using D3D and even Direct Draw. It works good on "toasters".

**Comment by Frank-74** [comment] 2018-12-01 22:40
@LegendOfDragoon Just use the latest nightly build: https://www.pj64-emu.com/nightly-builds

**Comment by Frank-74** [comment] 2018-12-01 22:58
I thought of one way to fix it, do whatever CTR+T+Enter does on openrom.  The settings window doesn't even have to display.  If you do CTRL+T+Enter, settings window doesn't even appear.  But it fixes this problem.

**Comment by project64** [comment] 2018-12-01 23:05
going in to settings even if you do not change anything will load other plugins .. so just loading jabo's plugin might do something to change it.

**Comment by Frank-74** [comment] 2018-12-01 23:13
I've just noticed on closing a ROM, Project64-Audio.dll and its thread closes fine. but dsound.dll still has 2 processes running.  One is DirectSoundCaptureEnumerateW (No unwind info), and the other is DllGetClassObjec (No unwind info).

**Comment by LegendOfDragoon** [comment] 2018-12-01 23:19
@Frank-74 Yea I had even tried that in a new directory and I couldn't reproduce it in Smash Bros the other day. I deleted it, so I'll have to make a another one lol.

I wonder if this issue is related to Windows timer resolution. When I open PJ64, the resolution stays the same, until I open settings tab. Jabo's Graphics plugin forces the timer resolution to change. Not sure why he'd do that for a graphics plugin lol.

**Comment by Frank-74** [comment] 2018-12-01 23:29
@oddMLan Discord is currently updating itself...  Last time opened was March I think...

**Comment by oddMLan** [comment] 2018-12-01 23:41
@Frank-74 Are you having problems with Discord?

**Comment by LegendOfDragoon** [comment] 2018-12-02 05:46
Welp, now PJ64 audio sets the resolution to 0.5ms. I guess this issue can be closed. I think 1ms would be a better default though.

**Comment by project64** [comment] 2018-12-02 06:13
I still need to see if this fixes all the issues

**Comment by oddMLan** [comment] 2018-12-02 06:59
9e35a1afc3b490ffb729c53980ef1164bdf31ae6 fixes the issue for me
However I agree with @LegendOfDragoon that 1ms would be a better default.
Also it would be better to set the timer when the audio thread is actually created and not on initialize, so just displaying the game list doesn't set the timer.

**Closed** 2018-12-02 07:01 UTC
Labels: Research Needed
