### ISSUE TITLE
Rat Attack not working in PJ64 2.X

### ISSUE THREAD

**Issue by theboy181** [project64/project64#62] opened 2015-02-07 06:46 UTC
Rat Attack is working in PJ64 1.X but not PJ64 2.X

**Comment by cxd4** [comment] 2015-02-07 15:14
I will check when I can.  We're undergoing a continual bed bug extermination process. :)

So when I get my laptop out for some wi-fi I try it.

**Comment by theboy181** [comment] 2015-02-07 17:42
That really sucks!!  There was this article from 2009. Not sure if it went anywhere but it's an interesting read. 

http://boingboing.net/2009/12/17/bug-powder-causes-ma.html

**Comment by cxd4** [comment] 2015-02-07 22:41
lol, that is interesting.  I just know the method they used to exterminate the critters here, wasn't that.

Right, then.  I've just tested and Rat Attack does fail in the interpreter core for the current Project64 2.x.  However, it boots up just fine in Project64 1.7.0.50 alpha 23 ... so there must have been a recent regression that happened to break it.  I will see if I can't isolate it.  I need to build together a full list of all the 1.7.0.50 alpha EXEs anyway to debug a separate problem @Predator82Germany is having with N-Rage.

**Comment by cxd4** [comment] 2015-02-07 23:40
Okay, just compiled and tested a EXE of pj64 from a commit from way back:
https://github.com/project64/project64/blob/86397d912c52bbcb2cb01bc71928db7270e566d6/Source/Project64/N64%20System/Interpreter/Interpreter%20Ops.cpp#L1141

When I start up Rat Attack it spams the "SH TLB" error message multiple times.

That, and the **current** Project64 2.2 from this repo has a breakpoint/crash in Interpreter Ops.c...so I suppose that Rat Attack fails because of a regression in the SH interpreter?  More investigation pending.

**Comment by cxd4** [comment] 2015-02-07 23:45
`	if (m_TLB_WriteMap[VAddr >> 12] == 0) { return FALSE; }`
Seems that is the condition causing the breakpoints in Rat Attack which fail pj64.

I don't know anything about TLB though.  Less a R4300i person, more a RSP person.  Still testing

**Comment by cxd4** [comment] 2015-02-08 01:29
Unfortunately the issue seems to go further back than alpha 45 of 1.7.0.50.
https://github.com/project64/project64/tree/dae4e73c89ab594783309d58db553d978e1aa186

Anything beyond that, I have to install MSVC 6.0 to compile it...I have not had VC6 on my computer for years now though might be able to try finding it again.

In the meantime all I can say is that Rat Attack broke SH TLB somewhere after 1.7.0.50 ver 23, and somewhere before 1.7.0.50 ver 45.

**Comment by theboy181** [comment] 2015-02-08 01:32
Your defiantly a trooper! I tried this game on my devcart and althought its a PJ64 issue it might not be worth the effort as the game is kinda bland. ;)

Would be great to see it back though. I have tried to load the game on other emulators and iirc none of them could load it either so I'm sure the fix will benifit the entire scene.

**Comment by theboy181** [comment] 2015-02-14 05:28
I thought I read a post that said this issue was resolved? any truth?

**Comment by LegendOfDragoon** [comment] 2015-02-14 07:05
It hasn't been committed yet lol. Be patient xD.

**Comment by cxd4** [comment] 2015-02-14 13:50
Supposedly dsx found an RDB fix for it.  I'd be amazed if he actually figured out Git to get a working pull request, but it sounds like he might have that done tonight.

**Comment by theboy181** [comment] 2015-02-14 16:47
after I read that it was the RDB I got it loading to the menu but then it crashes. I find this odd that no other emulator has this game loading if the RDB is the only issue. Guess we will have to wait till he releases the settings for me to test.

**Comment by Frank-74** [comment] 2015-02-18 08:18
I posted RDB settings [url=http://forum.pj64-emu.com/showpost.php?p=60114&postcount=81]here[/url].

**Closed** 2015-03-02 15:18 UTC
