### ISSUE TITLE
(VS2015) Opening settings menu crashes emulator

### ISSUE THREAD

**Issue by tony971** [project64/project64#689] opened 2015-10-26 06:25 UTC
Happens with all build configurations. Release builds simply close the window with no warning. Debug x32 gives the following error:

    Debug Assertion Failed!
    
    Program: ..\Project64.exe
    File: C:\Program Files (x86)\Microsoft Visual Studio 14.0\atlmfc\include\atlwin.h
    Line: 3191
    
    Expression: 0

**Comment by MELERIX** [comment] 2015-10-27 03:03
confirmed, same issue here.

**Comment by JunielKatarn** [comment] 2015-10-27 03:07
That file rings a bell. Take a look at one of the changes merged yesterday. (I did not touch that code, though).

FWIW, my automated build gets the same behavior since today.

**Comment by MELERIX** [comment] 2015-10-27 03:12
btw, seems only x86 version is affected, x64 opens the menu normally.

**Comment by tony971** [comment] 2015-10-27 14:16
I discovered this error on x64. It definitely affects it for me.

**Closed** 2015-10-27 22:51 UTC
