### ISSUE TITLE
[Game] Mystical Ninja Starring Goemon does not work

### ISSUE THREAD

**Issue by knuxyl** [project64/project64#1235] opened 2016-12-09 19:38 UTC
There is still major graphical and speed issues with this game. Can drop to around 12 FPS at certain places, glitchy graphics, and a very common problem across like all graphics plugins is when you go to start new game there is box glitch. Pretty much all games work, why is the ones that don't work not being worked on? I've seen absolutely no progress, probably even more problems, from PJ64 1.6 to now on this specific game. I've been waiting to play this since I had it on N64 like 20 years ago. I support the continuing project, I just wish yall would accomplish something that literally no N64 emulator on any platform has ever done, successfully emulate this game.

**Comment by oddMLan** [comment] 2016-12-09 21:10
This is not an emulator core problem. Use GLideN64 with it. Though it is still a pretty resource-hungry game, it runs decently at 2x native res in my computer. For extra speed you can also use Azimer's HLE audio plugin.

**Comment by Frank-74** [comment] 2016-12-09 21:25
Best performance I get is with Jabo's D3D8 1.6.1 plugin and counter factor=2.

1.6.1 plugins.
http://www.jabosoft.com/downloads/files/pj64plugins.zip

Put a 1.6 rdb in the emulator folder, otherwise, settings will corrupt when using 1.6 jabo gfx.

**Comment by Frank-74** [comment] 2016-12-09 23:03
Also you can try this version of Azimer XA2 0.7 I just built.  I removed everything unuseable from the dialog.
Just needs a simple config.bin to remember the settings.

https://dl.dropboxusercontent.com/u/9498358/n64/AziAudio.dll

Make sure to turn HLE audio on.

**Comment by LegendOfDragoon** [comment] 2017-01-04 18:51
Pretty sure Rice Video is the fastest plugin for this game, so I'd just use that if performance is an issue. But maybe Glide64 using nGlide is a better option (really depends on the game). I think Rice Video is good for games like Bangaioh.

Honestly for you own good, if you're not willing / able to help improve emulation, there's no point in nitpicking. You just have to accept things for the way they are. If you're really interested in seeing things improve, then you must take initiative and contribute.

>Also you might need something more than integrated graphics to run it decently. If you have Intel HD graphics then... I got bad news for you.

My Intel HD 530 is more than good enough for N64 emulation :smile: . Don't know of a single game I can't run full speed. My only issue is no Vulkan support, but I'm not even sure if Vulkan even lives up to the hype. Even older ones are fine for N64 if you use D3D. Hardware isn't the problem, it's the software.

>I've seen absolutely no progress, probably even more problems, from PJ64 1.6 to now on this specific game.

Sounds like you haven't done enough testing. PJ64's latest core has some significant improvements in performance, compared to version 2.1 and below.

Hopefully using Angle will make PJ64Video faster :smile: .

**Comment by LegendOfDragoon** [comment] 2018-03-29 17:54
This game works fine in PJ64, so this issue can be closed :smile:

**Comment by knuxyl** [comment] 2018-03-29 18:51
No it does not, you apparently havent played the original. Theres opcodes that are not correctly implemented. Game lags and there is not supposed to a black screen for 2 seconds over the sky in the beginning cut scene. Game is not playable because of the lag, this is either a 60 or 30fps game and whichever one it is I guarantee it doesnt run at it 100% of the time. Also starting a new game has graphical issues on the menu. Please stay out of comment section if u dont know what ur talking about because i want these problems resolved and if i didnt reply to ur comment theres a chance the issue wouldve been closed. You are wrong about the game working fine.

**Comment by LegendOfDragoon** [comment] 2018-03-29 19:48
>Theres opcodes that are not correctly implemented.

Such as??

>Game lags and there is not supposed to a black screen for 2 seconds over the sky in the beginning cut scene.

The problem is your setup, not Project64.

>Please stay out of comment section if u dont know what ur talking about because i want these problems resolved

How about actually listening to others instead of ignoring them and assuming you're right on everything and they are wrong?

Next time, submit a real issue and provide necessary information. You haven't even posted your specs because even my "toaster" can run the game at full speed on some plugins.

If you really are that concerned with using your favorite HLE plugin, it's a waste of time creating issues for every game because it just floods the issue tracker and makes it more difficult to focus. If you want accuracy, use LLE. Expecting perfect accuracy in every game with HLE is unrealistic.

**Comment by LegendOfDragoon** [comment] 2018-11-14 21:42
@project64 can you can close this? The game certainly works fine.

**Comment by cxd4** [comment] 2018-11-15 03:07
_"if i didnt reply to ur comment theres a chance the issue wouldve been closed"_

(Goes back to never replying to anything.)

(RPG replies to his reply with only **reasons** for closing, not a decision to do it.)

(Still ignores everyone.)

(8 months later)

(RPG replies with a **decision** to close, not reasons for closing.)

"OMG DRAGOON DIDNT U HEAR ME THE FIRST TIME?"

**Comment by cxd4** [comment] 2018-11-15 03:12
Not just RiceVideo but Rice 5.9.9.  You don't want to use 6.1.0 or the latest versions of Rice because the skybox hack works best with the legacy 5.9.9 release.  It's a hack, but ultimately the game runs at full speed with the lagging completely gone and the skybox being displayed by force.

**Closed** 2018-11-15 05:43 UTC
