### ISSUE TITLE
N-Rage 2.3 can't create new MemPak.

### ISSUE THREAD

**Issue by AmbientMalice** [project64/project64#34] opened 2015-01-27 10:18 UTC
Attempting to create a new MemPak immediately crashes the emulator.

The only entry in the log file is this.

2015/01/27 20:20:28.174 01176: Error  : WinMain: Exception caught (File: ".\main.cpp" Line: 401)

**Comment by Predator82Germany** [comment] 2015-01-27 11:20
With 2.1.0.1? I have no crash

**Comment by AmbientMalice** [comment] 2015-01-27 13:25
Using the latest binaries compiled from emucr.

**Comment by Predator82Germany** [comment] 2015-01-27 13:49
That´s the problem

**Comment by cxd4** [comment] 2015-01-27 16:59
Yeah, just use N-Rage 2.1.

I'm pretty sure squall would say N-Rage 2.3 doesn't have the crash either, if you just get it from him and nobody else's build of it.  But that goes probably for the PJ64 build also, just not EmuCR.

**Comment by Frank-74** [comment] 2015-02-22 09:31
Same thing happens with PJ64_NRage.  New Mempak Browse crashes emulator.

**Comment by Predator82Germany** [comment] 2015-02-22 16:38
Happens here too

**Comment by cxd4** [comment] 2015-02-22 16:46
squall said something about fixing a crash with N-Rage 2.3 but not introducing one.

IIRC he usually got mad at people using builds of N-Rage 2.3 which were not distributed by him, citing something about the way that the resources are getting linked to cause deviations like this.

**Comment by project64** [comment] 2015-02-22 21:46
I have renamed it now so there is no confusion over where it is built from.

I was thinking that it might be good to strip out the mem pak handling out of the plugin, no need to have it both in the core and in the plugin. Just get the plugin to go through the core if mem pak is installed.

**Comment by Frank-74** [comment] 2015-02-22 22:12
There's already an option to uncheck RawData, which allows the emulator to handle the mem pak.
Its handy having NRage handle mempak's as it allows saves to be used across different emulators.

I remember Shunyuan fixed this bug in 2.3c lite.  But he also removed XInput.

**Comment by project64** [comment] 2015-02-22 22:23
the version of nrage ( a fork of it) I am using I am looking at getting better integration in with the core, so not looking as much as it being used on other emu's, even tho it should still be able to. 

I am just looking at where it makes sense to remove options, since those values are already there in the core no need to have it twice, with possible bugs one way but not the other, better just to maintain it all in one location.

**Comment by cxd4** [comment] 2015-02-22 23:08
Most emulators have mempak supported within them, but N-Rage usually handles it more accurately.

For example if you use Jabo's DirectInput, the mempak is 128 KB which is wrong.  So it's probably handled better from within N-Rage's mempak code.

**Comment by project64** [comment] 2015-02-22 23:20
it would be better then put that fix in to the core if it is wrong.

**Comment by Frank-74** [comment] 2015-02-22 23:27
It would be good to replace the core mempak code with NRage's.  You can then remove the Current MemPak Directory dialogue, and have each game have its own MemPak as usual.  But keep the MemPak Content dialogue so we can format and save/insert/delete MemPak notes.

And if NRage is replacing Jabo as the default, makes sense to also use NRage's mempak code in the core.

**Comment by project64** [comment] 2015-02-22 23:42
yes, it is replacing it from 2.2 onwards, since it is open source then I can get a tighter coupling with it. When I look at removing it I can try to see what is different/better with the core and integrate those changes if there is any.

**Comment by AmbientMalice** [comment] 2015-02-22 23:50
The biggest problem with mem pak emulation is the need to swap mem paks because there's only 256kb of data to use and some N64 titles use obscene chunks of that. Giving each game its own mem pak file is one solution, but not a particularly elegant one.

**Comment by project64** [comment] 2015-02-23 00:00
I believe the core give each game there own mempak. 

is there any advantage of sharing the mempak's between games

**Comment by Frank-74** [comment] 2015-02-23 00:22
There are occasions where I need a new mempak for the same game, for example when I start the next season in Monaco GP2 in Career mode.  PJ64 would have to append a number to new mempak's, i.e. Monaco GP Racing 2_2.mpk, and allow for selecting MemPak 1, 2, or 3 etc.

**Comment by cxd4** [comment] 2015-02-23 00:28
> only 256kb of data to use

Only 256 Kb as in bits, yes, but not kilobytes.
That probably is why pj writes the wrong file size.  Somewhere it's documented that mempaks are "256K", but I'm pretty sure by that they meant 256 Kbits = 32 Kbytes, not 256 kilobytes.  You have 128 pages * 256 bytes per page, = 1 KiB per every 4 pages = 128/4 = 32 KiB.

> is there any advantage of sharing the mempak's between games

IDK, maybe not.  Some people are familiar with the N64 feature that you can hold down START button when a rom boots up that uses the mempak, and it has its own controller pak file system manager built into the game, and maybe some people prefer that interface and like to have all their mempak data into a single mempak rather than 256 KB per every rom.

**Comment by Predator82Germany** [comment] 2015-02-23 06:57
Imho N-Rage should handle MemPaks alone, did work from first withmempakhandle N-Rage why change that? (never change a running system
& 1 MemPak for 1 game is (sorry) bullshit, then comes an cfg.ini for each game ;) ... to much files

**Comment by cxd4** [comment] 2015-02-23 15:12
I wouldn't mind moving N-Rage mempak handling to Project64 core if it meant fixing the inaccuracy.

The advantage to having 1 MemPak per 1 game is not having to change mempak all the time in case you run out of space, though usually it is very rare and hard to run out of space...most games only use 2 pages of mempak data (512 bytes).  Mario Kart does use 121 pages, but it's for complete garbage no one cares about.

The disadvantage is that when you access the controller pak file menu in-game or using N-Rage interface for it, you can only see game pages/notes for one mempak at a time because PJ64 created them 1 game at a time rather than all-in-one.  Maybe in the future if this became that much annoying pj64 could be changed to just allocate 1 MPK per plugged in controller or something, and if running out of space in the mempak could be an issue people would either switch controllers or backup, rename mempak.

**Comment by AmbientMalice** [comment] 2015-02-23 21:52
It is very easy to run out of mem pak space. Obviously you've been playing the wrong games.

**Comment by death-droid** [comment] 2015-02-27 11:06
The reason Project 64s handling of the Mempak is the incorrect size is because it stores a mempak for all 4 possible controllers within the same file.

**Comment by cxd4** [comment] 2015-02-27 17:20
That would not be a valid mempak file.  Nothing in the specifications permits merging 4 controllers into one, and I didn't think anyone working on an emulator would care to do that...?  Because people play with just one controller when emulating almost all the time.

**Comment by cxd4** [comment] 2015-02-27 17:22
Your theory only holds up @death-droid if the MPK files from PJ64 were 128 KB but they're not.

A mempak is 32 KB, not 256 KB.

256/32 is 8, not 4, so it's not the number of controllers.

**Comment by death-droid** [comment] 2015-02-28 00:46
"That would not be a valid mempak file. Nothing in the specifications permits merging 4 controllers into one, and I didn't think anyone working on an emulator would care to do that...? Because people play with just one controller when emulating almost all the time."

Doesn't merge all 4 controllers into one, just saves the mempaks in one singular file, they are still read back into the emulator as 4 separate mempaks.
Also its not a theory, its exactly how the code works. Theres an odd problem with having all 4 mempaks stored in the same file that causes it to increase beyond 128.

I've tested my modified version of the code, and it indeed creates the saves at 32kb, I can upload them if you don't believe me.

**Comment by cxd4** [comment] 2015-02-28 01:11
After having just decided to take a look at `mempak.cpp`, I can see that this module is indeed merging 4 controller mempaks to a single file.  I could push some improvements to mempak handling there.

"Why is it 256 instead of 128 KB," you ask?  That's less how "the code" works, more how the compiler works.  When you take sizeof of something with a complex allocation, the result is not implementation-defined behavior but unspecified.  An array of arrays is never said to be all contiguous.

**Comment by death-droid** [comment] 2015-02-28 04:01
Ahhhh cheers for that explanation! Learnt more from that then darn Uni lectures

**Comment by Frank-74** [comment] 2015-02-28 10:06
Fixed the New MemPak/Browse button crash.

**Comment by Lithium64** [comment] 2015-02-28 10:08
I can reproduce this bug too
https://www.youtube.com/watch?v=wm85b1qtnws

**Comment by death-droid** [comment] 2015-02-28 11:12
@Frank-74 while yes it does fix the crash, it is actually breaking the original intention of that code >.< So not really a proper fix.

**Comment by cxd4** [comment] 2015-03-03 20:39
Man GitHub notifications really sucks.  It keeps randomly skipping over certain topics.

> Ahhhh cheers for that explanation! Learnt more from that then darn Uni lectures

I don't remember where or how I learned it.  Hell, don't remember where or how I even learned anything about C programming.  I just remember deducing that sizeof is a bit more of a unary/types thing--one of the rare differences where saying an array name versus a pointer to memory matters.  In fact the pj64 RSP has a "bug" that's fixed by the same undefined behavior related to sizeof from counting past the end of inside a two-dimensional array.

**Comment by project64** [comment] 2015-03-25 21:11
have nrage now defaulting to mempak (https://github.com/project64/project64/commit/b3aaef221c0fd19af648fb3ab6b4168bef63c813) and when mempak is enabled do not allow raw mode (https://github.com/project64/project64/commit/061fbefa62b52e58aa47a6b788bd9907d4cfa686)

I still need to update the ui to represent this. 

I can then strip all the code related to mempak from nrage after this, but I could release in theory with out this.

**Comment by cxd4** [comment] 2015-03-25 22:45
Depends how time-consuming it would be I guess.  Delaying the removal of the mempak handling from N-Rage until after 2.2 would just mean temporarily larger file size.

Normally I'd say keep it, but this fork of N-Rage uses its own controller spec for integration with pj64 so nah, probably better just remove.

What about the crash issue with 2.3 mempak @AmbientMalice?  I saw Frank-74 seems to have fixed that, or is some issue still left with it?

**Comment by AmbientMalice** [comment] 2015-03-26 01:25
@cxd4 N-Rage mem paks seem to work fine now.

**Comment by LegendOfDragoon** [comment] 2016-01-27 01:09
Is this still an issue?

**Closed** 2016-01-27 03:06 UTC
