### ISSUE TITLE
Games slow if no entry in Project64.cfg

### ISSUE THREAD

**Issue by AmbientMalice** [project64/project64#376] opened 2015-04-14 03:55 UTC
This affects a number of games. For this example, I will use Duke Nukem 64 (U).

Install clean emulator. (Or delete Project64.cfg)
Start Duke Nukem.
Watch the framerate plummet for no apparent reason, with high r4300 usage.
Now add the following to Project64.cfg

[A273AB56-DA33DB9A-C:45]
Good Name=Duke Nukem 64 (U)

And presto, the problem is magically gone.

**Comment by Lithium64** [comment] 2015-04-14 11:38
This bug happens here on some games like 1080 snowboarding, Automobili Lamborguini, Cruis'n Usa, Cruis'n Word, Power Rangers and others

**Comment by Predator82Germany** [comment] 2015-04-14 12:04
Set sync using audio off

**Comment by AmbientMalice** [comment] 2015-04-14 12:38
@Predator82Germany All that matters is the game has an entry in the cfg file. If it's missing, the game is slow. If it is present, the game runs normally regardless of Sync being on or off. In this case, Duke Nukem is fine with Sync Audio. (That said, the game's audio seems to be too fast with Jabo compared to Azimer's.)

**Comment by Lithium64** [comment] 2015-04-14 16:36
I reported this bug once, but HatCat said it was a problem on my PC, however I tested on another PC with Windows 8 and the bug happens there too.

**Comment by cxd4** [comment] 2015-04-14 21:59
@Lithium64:  You'll have to refresh my memory on the part where you said that your RDB had a missing entry for the game, because that's what AmbientMalice is talking about.  You're bringing up a past issue out of context; the issue in THIS discussion is about what happens when loading a ROM with absolutely no entry at all in the CFG file.

**Comment by AmbientMalice** [comment] 2015-04-14 22:09
It's likely just a coincidence that 1080 is one of the games affected by this problem.

It is slightly possible that cfg file corruption could contribute, but I'm doubtful.

**Comment by Frank-74** [comment] 2015-04-14 22:32
For any game running without opening edit game settings or changing plugins, PJ64 doesn't write an entry into the cfg file.

Duke Nukem 64 is a good example.  If you run without an entry in the cfg its really slow.  However, while the game is running real slow,  open Options/Settings/Config:Duke Nukem 64 (U), and check and uncheck any item and hit apply, close settings and game will be at 60 VI/s.

**Comment by Lithium64** [comment] 2015-04-15 03:38
@cxd4 It is the same bug that I reported to u one time on IRC about 1080 snowboarding, I think I didn't explain properly how to reproduce the bug

**Comment by AmbientMalice** [comment] 2015-04-15 06:23
This is a serious bug. Assuming it is universal and not just restricted to certain PCs, it means dozens of games are basically unplayable on PJ64 2.2 and current builds out of the box.

**Comment by cxd4** [comment] 2015-04-15 17:44
You just don't get it @Lithium64.  You kept changing the CFG settings for 1080 and updating the `Project64.cfg` file in an attempt to fix your 1080 slowness issue Lithium ... that proves this has nothing to do with your issue, because it is about the CFG file having NO entry at all for 1080.  You created and modified one many times.

Besides, that issue you had was more along the lines of VI fluctuation, with a slight offset from 60 and audio timing.  Seriously.

**Comment by Lithium64** [comment] 2015-04-15 20:33
@cxd4 The issue is the same, when I add one entry for 1080 avalanche on CFG the game run on full speed. I figured this after I spoke with you that day. You don't have to change any settings, just add one entry for the game on .cfg file.

**Comment by Lithium64** [comment] 2015-04-16 05:47
@AmbientMalice I made some tests here, this bug is very old on 2.0.0.14 this bug already happens, latest build free of this issue is 1.7 leaked beta.

**Comment by AmbientMalice** [comment] 2015-04-16 06:48
@Lithium64 I believe the slowdown issue began recently. There is an unrelated problem that also causes slow speed in older builds - FAT and Audio Sync were both enabled in older builds.

**Comment by theboy181** [comment] 2015-04-16 18:53
I think the .CFG corruption issue was resolved in current builds. Are you compiling PJ yourself?

**Comment by AmbientMalice** [comment] 2015-04-16 21:45
Yes, I compile myself. No, it is not fixed. At least it wasn't fixed as of yesterday. Plugin switching is the thing I associate with it most strongly.

**Comment by theboy181** [comment] 2015-04-16 21:52
https://github.com/project64/project64/pull/377

That seemed to fix my issues. But can you reproduce the project64.cfg corruption consecutively?

**Comment by theboy181** [comment] 2015-04-16 21:59
EmuCR builds have the .cfg file linked to the users profile in a folder called config. It took me a while to realize that I had a corrupted cfg file there when I was testing some EmuCR builds earlier this week. 

Oh EMUCR!!!!

**Comment by Frank-74** [comment] 2015-04-16 22:03
@AmbientMalice I think the cfg corruption happens when switching to/from 1.6 plugins.  Corruption starts in the 1.6 rdb because plugins don't read the first line of the rdb (but they write to it).  Old blank dummy rdb had a '//' with a comment on the first line.  Corruption of cfg started when the blank rdb was removed.  I've had no corruption at all for a couple of weeks.  Made a 1.6 rdb in the Suggestions forum for this purpose.  It has all the Jabo settings from the 2.2 rdb.

**Comment by theboy181** [comment] 2015-04-16 22:08
@frank-74 are you talking about 1.6 plugins getting used on 2.3 Pj or sharing your pj directory with older versions of pj. 

I think older versions of pj can corrupt your cfg file too.

**Comment by Frank-74** [comment] 2015-04-16 22:11
Yes, 1.6 plugins used with 2.0+.  If you have no Project64.rdb in the root folder for 1.6 plugins, with a // comment on the first line, you'll sometimes get corruption in the cfg file when switching to/from 1.6 plugins.

**Comment by AmbientMalice** [comment] 2015-04-17 01:34
@Frank-74 and @theboy181, I've been testing today's source with a certain video plugin that may or may not have leaked onto reddit, and I haven't had any crashes when switching plugins and no cfg corruption, either. So I'm assuming a recent commit has cured the crash problem.

**Comment by Lithium64** [comment] 2015-04-17 01:46
@AmbientMalice I think i found the origin of this issue
https://github.com/project64/project64/commit/6936cd980086e9dfb46f89e03dfee15288350644

**Comment by AmbientMalice** [comment] 2015-04-17 01:54
@Lithium64 
>13 Feb 2013
Well, it fits the timeframe perfectly - two months before 2.0 was open sourced. Any idea what aspect of the code is broken? (I wonder how far reaching this bug actually is. Only a few games suffer serious slowdown. But suppose it could cause CPU usage spikes in every game or worse?)

**Comment by Lithium64** [comment] 2015-04-17 01:58
@AmbientMalice I don't know where the code is broken, but this commit could be the origin of the bug.

**Comment by Frank-74** [comment] 2015-04-17 02:16
Leaked plugin doesn't work here, I get an invalid win32 exception in Project64.exe.  I guess my gfx doesn't meet the minimum requirements.

**Comment by AmbientMalice** [comment] 2015-04-17 02:17
It requires OpenGL 4, I believe. What is your GPU, anyway?

**Comment by Lithium64** [comment] 2015-04-17 02:21
@AmbientMalice it won't work here too, my gpu is amd hd 4650

**Comment by AmbientMalice** [comment] 2015-04-17 02:22
@Lithium64 according to this, your GPU is a notebook GPU that only supports GL 2.0 http://www.notebookcheck.net/AMD-ATI-Mobility-Radeon-HD-4650.13883.0.html

**Comment by Frank-74** [comment] 2015-04-17 02:32
Radeon Xpress 200 in PC.  And Intel gfx in Atom notebook with Windows 8.1.  Works on neither.

**Comment by Lithium64** [comment] 2015-04-17 02:36
@AmbientMalice Mine gpu is this
http://www.newegg.com/Product/Product.aspx?Item=N82E16814150396

**Comment by AmbientMalice** [comment] 2015-04-17 02:39
>http://www.newegg.com/Product/Product.aspx?Item=N82E16814150396

It's an OpenGL 2 card.

>Radeon Xpress 200

That's also OpenGL 2.

OpenGL 4.0 was released in March 2010. So anything made before that date won't run GLideN64 in its current state as far as I know.

**Comment by Lithium64** [comment] 2015-04-17 02:40
@AmbientMalice It received a driver update with OpenGL 3.3 support

**Comment by AmbientMalice** [comment] 2015-04-17 02:42
>It received a driver update with OpenGL 3.3 support

AFAIK, 3.3 isn't good enough. I believe that's why GLideN64 hasn't been ported to Mac yet, because mupen64plus on Mac doesn't support GL 4.0

**Comment by Lithium64** [comment] 2015-04-17 02:46
@AmbientMalice I think it is time to buy a new gpu

**Comment by AmbientMalice** [comment] 2015-04-17 02:49
It is possible GLideN64 might be altered to run on SLIGHTLY older GPUs. I certainly can't imagine Zilmar being 100% happy if PJ64 will only run properly on GPUs made after 2010.

**Comment by project64** [comment] 2015-04-17 02:53
if I ever had it in pj64 it would probable need a test to see if the gpu supported it, if it did then set it as a default if not then set another more compatible plugin as the default.

**Comment by AmbientMalice** [comment] 2015-04-17 03:01
>if I ever had it in pj64 it would probable need a test to see if the gpu supported it, if it did then set it as a default if not then set another more compatible plugin as the default.

I suppose Glide64 can hang around as the fallback?

**Closed** 2015-04-19 22:50 UTC

**Comment by project64** [comment] 2015-04-19 22:53
I think the https://github.com/project64/project64/commit/edda4f055506e3aefcba6b13b6431916d946c618 does fix it, if not I will reopen it.

**Comment by AmbientMalice** [comment] 2015-04-19 23:02
@project64 out of curiosity, what was the emulator doing wrong?

**Comment by project64** [comment] 2015-04-19 23:25
nothing wrong, the setting system is slow, well not horrible slow that it needs to be removed just the results need to be cached for good performance. For check interrupts it was calling out to the settings system 100's maybe 1000's times per second, which cause a huge performance degradation.

When there was an entry in the cfg file it could cache that result (still getting a performance degradation), when no entry since it had no cached results it was scanning more information trying to find what was not there (bigger degradation)

**Comment by Lithium64** [comment] 2015-04-20 21:22
@project64 I'm tested it here and the issue was fixed, thank you brother this is a great fix!
