### ISSUE TITLE
N-Rage resets when controllers are disconnected.

### ISSUE THREAD

**Issue by AmbientMalice** [project64/project64#888] opened 2016-01-17 07:32 UTC
This is kind of a serious bug. Basically, any and all bindings are flushed if the controller associated with them is not connected when N-Rage is opened.

**Comment by tony971** [comment] 2016-01-27 15:18
I hope this is fixed by 2.3

**Comment by Squall-Leonhart** [comment] 2017-05-12 19:22
intended behavior tbh,  the mapping is associated to the gamepad guid.

**Comment by tony971** [comment] 2017-05-12 21:54
> intended behavior tbh, the mapping is associated

Well that's pretty shitty. It has all of the conveniences of hot plugging but exactly the opposite. If I plug in a controller that has already been mapped, it shouldn't require any new configuration to use again.

**Comment by project64** [comment] 2020-04-28 11:16
closing old issue, if this is still an issue it can be reopened

**Closed by project64** 2020-04-28 11:16 UTC
