### ISSUE TITLE
Save (F5) and Load (F7) broken

### ISSUE THREAD

**Issue by ePSXe205** [project64/project64#1207] opened 2016-09-19 09:19 UTC
The save/load function still works fine for me on version 1.6 -> 2.2.0.3. But since version 2.3, it gives me an error: "unknown memory action emulation stopped". If I uncheck "automatically compress saved states" then I can save, but when trying to load, the game crashes and a message appears saying "fatal error emulation stopped".... I already tried many plugin combination/setting but none of it's working. 

I am running Windows XP Service Pack 2, Intel GMA X4500 GPU. Would be very grateful if you can fix it, thanks in advance!

**Comment by Frank-74** [comment] 2016-11-13 22:05
XP sp2 is REALLY old.  Service pack 3 was released in April/May 2008.  That's over 8 years ago.

I had XP SP3, it was rock solid and fast.  The only reason I left it was my pc power supply exploded and caught my pc on fire.

**Comment by ePSXe** [comment] 2016-11-15 10:26
Hello, I found the root cause to the problems. It happens since those commits on Apr 20 and Apr 21, 2016:
+ Get load save state to use cfile
+ Make saving states more cross platform

Please take a look at this page for more info: https://github.com/project64/project64/commits/05eb9f1d76986fb4fd5ac70d212666a5367cce51

The Git build from Apr/19 still works fine for me. Anyone can undo the change in future release?

**Comment by Frank-74** [comment] 2016-11-18 02:29
Compressed save and load works ok on 8.1.

Uncompressed save works, but load gives this error:
> 2016/11/18 02:27:36.906 03528,Error,User Interface,CNotificationImp::DisplayError,Break point found at
.\N64System\Mips\SystemTiming.cpp
376

Extrainfo .dat file becomes 0kb after trying to load uncompressed save.

**Comment by project64** [comment] 2016-11-18 02:40
interesting that should be easier to find and fix

**Comment by Frank-74** [comment] 2016-11-21 03:10
Commenting out this section in N64System/Mips/SystemTiming.cpp allows the uncompressed save to load correctly.

```cpp
    if (TimerDetailsSize != sizeof(TIMER_DETAILS))
    {
        g_Notify->BreakPoint(__FILE__, __LINE__);
        return;
    }
    if (Entries != sizeof(m_TimerDetatils) / sizeof(m_TimerDetatils[0]))
    {
        g_Notify->BreakPoint(__FILE__, __LINE__);
        return;
    }
```

**Comment by Frank-74** [comment] 2016-11-21 14:18
@project64 
XP works fine with compressed save states, if built with VS2008.  VS2015 breaks something for XP.

XP SP2 and 8.1 work with both uncompressed and compressed save states with the above code commented out.  Though uncompressed saves are unreliable when loading, sometimes works ok, sometimes not.

**Comment by Frank-74** [comment] 2016-11-21 15:46
I found the problem with extrainfo .dat being wiped.  Uncompressed saves load ok now.
https://github.com/project64/project64/pull/1218

**Comment by Frank-74** [comment] 2016-11-21 19:28
Can be closed, it's fixed now.

I will try to tidy up the save/load source, so it doesn't need to keep checking if zipped saves are selected.  Also, try to get it to attempt load of compressed save if it can't find uncompressed, and vice versa.  So that you can load and save to any format.

**Comment by Frank-74** [comment] 2016-11-23 18:58
Project64 forum PM from cloudstr, aka @ePSXe205.

> Hello, this sound embarrassing here, but I forgot the password of my "ePSXe205" account that created the thread. Perhaps kind of random characters that come flying across my head.
>
> I'm affraid I can't close it. Hope this does not cause any inconvenience for anyone.

This issue should be closed.  Also, #667 is fixed with #1218.

**Comment by LegendOfDragoon** [comment] 2017-01-13 01:22
@project64 I guess you can close this.

**Closed** 2017-01-13 21:01 UTC

**Comment by Javain** [comment] 2019-10-05 17:36
I'm getting this very same issue running windows 10 version 2.3.2.202

**Comment by oddMLan** [comment] 2019-10-05 18:45
@javain  that version is not current, try using the latest nightly build from https://www.pj64-emu.com/nightly-builds
download the zip and extract to fresh directory

then let us  know if you still have the same issue
