### ISSUE TITLE
Failed to open Transferpak ROM, ERROR

### ISSUE THREAD

**Issue by MelchiorGaspar** [project64/project64#989] opened 2016-02-08 18:46 UTC
While this error does not prevent the ROM from loading(once clicked upon) it is however annoying.

this error occurs after clicking to open a ROM.
![projet64_exceptions6](https://cloud.githubusercontent.com/assets/1712842/12895330/eb30c090-ce69-11e5-8e43-fd1005878cd5.jpg)

**Comment by JunielKatarn** [comment] 2016-02-09 01:41
This looks like a duplicate from #980. Please close.

It's a minor bug which shouldn't affect emulation.

**Comment by JunielKatarn** [comment] 2016-02-09 01:43
@death-droid More users are running into this issue. Do you think we could have a fix soon? Maybe at least comment out the TransferPak initialization call, while the validation logic is corrected?

**Comment by cxd4** [comment] 2016-02-16 20:22
@MelchiorGaspar I seem to be hearing from everyone that this issue is fixed.  What do you think?

**Comment by JunielKatarn** [comment] 2016-02-16 22:34
Not that anybody asked me XD, but I insist that this is a duplicate of #980, which has been fixed.
This one should be closed too.

**Comment by vgturtle127** [comment] 2016-02-17 03:19
@cxd4 I believe this is fixed, TransferPak messages should be restricted to games that support the TransferPak anyway. :smile:

**Comment by cxd4** [comment] 2016-02-17 04:13
I was asking simply him for the purposes of verifying that he should close this pull request.  I'm not involving who reports what first or what's a duplicate of who or did the cake kill the lemon, or why didn't SSJ4 Gogeta fuse with Omega Shenron.

>TransferPak messages should be restricted to games that support the TransferPak anyway. 

I'm hoping you had noticed this, but that was precisely the issue being caused here.

Random ROMs like Absolute Crap don't even have anything to do with the transfer pak.  Hell, nothing but Pokemon does.

**Comment by MelchiorGaspar** [comment] 2016-02-17 14:09
it seems like its fixed the error is not occurring anymore.
so I guess you can go ahead and close it.

**Comment by cxd4** [comment] 2016-02-17 16:34
Well I can actually not; that's why I asked.

That and even if I can close issues, it's sort of a dick move since you reported, not me.

**Comment by MelchiorGaspar** [comment] 2016-02-17 17:58
ooh I see I can close the issue... O_o lol

**Closed** 2016-02-17 17:58 UTC

**Comment by vgturtle127** [comment] 2016-02-18 03:40
@cxd4 I was just reporting that the issue was fixed for me, and that I couldn't reproduce the bug on the latest build.

And I was aware that that was one of the issues here, that's why I said something about it. :grinning:

**Comment by TechionDigit** [comment] 2017-04-29 16:59
Just today I started my Project 64 and the error popped up.But my emulation WILL NOT START.It just goes black.Can anyone help?

**Comment by TechionDigit** [comment] 2017-04-29 17:01
Nevermind, just changed what PAK I was using. 😁
