### ISSUE TITLE
how to run the program on a PC with Windows 10?

### ISSUE THREAD

**Issue by leosmendes** [project64/project64#1158] opened 2016-07-12 13:02 UTC
this version is designed for computers running Windows? as the audio plugin that comes with the package is for android, and I could not use another audio plugin. besides it installed nglide, but only with error messages when trying to run a rom

**Comment by Frank-74** [comment] 2016-07-12 18:07
The audio plugin (by Jabo) is for Windows, it is before Android's time.  The install never installs nGlide either.  You get Glide64 for PJ64 in the install (or zip), which has the glide3x (glitch library), built in.  Never Glide64 Final and nGlide.

**Comment by vgturtle127** [comment] 2017-01-12 04:32
@leosmendes Are you having a specific issue? You weren't very clear as to what the issue is...

Did you get it to run or are you having issues with plugins?

**Comment by cxd4** [comment] 2017-01-14 02:53
His issue is/sounds like why is Project64 written for Windows instead of his Android phone.  omg wtf is this windows os and all the exe files 4 why wont this work on my smartscreen

**Comment by leosmendes** [comment] 2017-01-14 10:10
I would like to know what I need to add to the emulator to make it work on windows? I can not make it work on my pc with the pluguins that come with the package.

**Comment by cxd4** [comment] 2017-01-14 22:15
I would say add the installation using the installer, and the installed emulator should work on Windows.

**Comment by leosmendes** [comment] 2017-01-14 22:42
Great, now it worked, already ate forgot that you could have done it wrong

**Comment by cxd4** [comment] 2017-01-14 23:55
I just ate myself now already.

Which reminds me, on a related note:  Is the issue fixed now so that you could close it?

I had sweet & spicy almond salmon.  Bitch cost me $10.58 for only .46 pounds but man was it good.

Ingredients:
black pearl salmon, brown sugar (sugar, molasses), almonds, canola & olive oil blend, cumin, paprika, cayenne pepper, sea salt, black pepper, green onion.

**Comment by JunielKatarn** [comment] 2017-01-19 02:25
@leosmendes Is this still an issue? Can you please close if it's resolved?

**Closed** 2017-01-19 14:53 UTC
