### ISSUE TITLE
Mario Kart 64 multiplayer speed issues

### ISSUE THREAD

**Issue by MatthewHunter1983** [project64/project64#288] opened 2015-03-18 15:45 UTC
Mario kart 64 dk jungle parkway (among a certain few other courses) runs waaaaaaay too fast on modern machines in 2 or more player mode. it's always the same few courses (as I have seen in google searches. and this was even apparently glitch on the wii virtual store version of the game), this is just the course I test on. this is true on any operating system, emulator, and plugin 3d or not. screwing with refresh rates and regions can fix it but then other courses will be slower and this is no fix. from my searches I ascertained that the myth is that Nintendo hacked those courses somehow to run at acceptable framerates that were capped on the limitations of n64 hardware, but on newer/faster hardware, those few courses in multiplayer mode run waaay to fast. one person commented that it's staying true to the software but that is ridiculous. the game was designed to be played at an acceptable pace with no consideration to future emulation, which should remain true to the original experience if not enhance it where possible. and breakneck speeds are not an enhancement.

it makes the game unplayable in multiplayer mode :\ thanks again!

**Comment by cxd4** [comment] 2015-03-18 18:00
Yeah, there was a discussion about that issue here:
https://github.com/project64/project64/issues/32

So we do have an issue report already for the fact that Project64 can't automatically change the VI refresh rate dynamically as of yet (not like it revolves around a fully cycle-accurate background, so doesn't that is easier imagined than realized), so the issue is that VI refresh rate has to be set manually to work around it.

**Comment by MatthewHunter1983** [comment] 2015-03-19 20:02
awesome! thank you for the thrifty reply, and sorry for the double thread. tried searching a bit and didn't find the original. this was my first post here and I intend to contribute my experience with testing a lot :) I apologize in advance for any lamen's terms and verbose jargon I throw around. I try to be as accurate with technical jargon as possible. I do have a bachelor's degree in 3d animation but I know nothing of the miraculous coding etc. that goes on here. I just know what boxes to click to make my games look sweet. love the great work you folks do here and all the other emulator gits. super excited to see that this is being worked on :) great work, and thanks!

**Comment by LegendOfDragoon** [comment] 2015-03-25 00:22
Please close this issue, since there was already another discussion.

**Closed** 2015-03-25 03:48 UTC

**Comment by theboy181** [comment] 2015-08-27 02:45
Multiplayer speed fix
81001C90 240A
81001C92 0002
81001C94 240A
81001C96 0002
81001A38 2409
81001A3A 0002
81001A3C 2409
81001A3E 0002
