### ISSUE TITLE
GUI Main window moves position off screen.

### ISSUE THREAD

**Issue by exhalatio** [project64/project64#68] opened 2015-02-10 10:56 UTC
This issue in both Windows 8.1 and XP.
When Taskbar located at top edge or leftmost, move the window position each time.
Sure, Taskbar located in the default position (bottom edge), no problems.

**Comment by cxd4** [comment] 2015-02-13 02:28
I have access only to Windows 7 and am not able to reproduce your problem.  So do you think it's specific to just XP and Windows 8?

I moved my Windows taskbar to the left, top, and right of my desktop display and have no problems clicking and dragging the window position of Project64's window coordinates.  Might need somebody on Windows XP or Windows 8 to test ... @oddMLan you use Windows 8 don't you?

**Comment by oddMLan** [comment] 2015-02-13 03:13
Could reproduce. Let me do a video of the issue.

**Comment by cxd4** [comment] 2015-02-13 23:32
yeah not able to test, not sure but @exhalatio it seems as though this commit made earlier today might have an effect (hopefully positive) on your issue?
https://github.com/project64/project64/commit/811a41d494540596a61e8ea7a2cfe1bdd096af69

**Comment by exhalatio** [comment] 2015-02-14 03:30
this issue in this commit seems to be fixed both XP and 8.1.

**Comment by cxd4** [comment] 2015-02-14 03:38
Nice.  So you're saying that fixed the issue now?

If that's so you can either close this issue yourself or wait for the repo owner to close it.

**Closed** 2015-02-14 04:23 UTC
