### ISSUE TITLE
Fatal Error - Stopping Emulation -  Plugin Shunyuan's HLE

### ISSUE THREAD

**Issue by schubertguilherme** [project64/project64#1507] opened 2018-12-02 00:30 UTC
Fatal Error - Stopping Emulation in v2.4.0-722-gad19a6f last build.

**Comment by CrashOveride95** [comment] 2018-12-02 00:35
You have provided no details whatsoever. What game were you playing? what plugins?

**Comment by schubertguilherme** [comment] 2018-12-02 00:56
In all games when installing the emulator and I will choose the plugins.

![untitled](https://user-images.githubusercontent.com/36903073/49334399-4714c380-f5bc-11e8-830b-d95abc7f0f9a.jpg)

**Comment by CrashOveride95** [comment] 2018-12-02 00:58
what plugins?

**Comment by schubertguilherme** [comment] 2018-12-02 01:02
![2](https://user-images.githubusercontent.com/36903073/49334436-36b11880-f5bd-11e8-89bc-1580ac09610f.jpg)

**Comment by schubertguilherme** [comment] 2018-12-02 01:04
Here Shunyuan's HLE best audio plugin my computer.

**Comment by Frank-74** [comment] 2018-12-02 01:13
Try checking the Audio HLE box.

**Comment by cxd4** [comment] 2018-12-02 01:56
I thought his plugins originally working in earlier builds was the regression.  Wasn't that fixed?

**Comment by schubertguilherme** [comment] 2018-12-02 02:05
only version v2.4.0-706-g6a65305 works, all of them do not work.

**Comment by theboy181** [comment] 2018-12-02 02:14
Compatibility was removed due to the nature of the developer.

**Comment by schubertguilherme** [comment] 2018-12-02 02:33
> Compatibility was removed due to the nature of the developer.

Really?

**Comment by theboy181** [comment] 2018-12-02 02:57
I’m only joking, but I’m sure that it will be working soon. It was one of my favourite audio solutions.

**Comment by Fanatic-64** [comment] 2018-12-02 16:38
Well, the changes made to implement the Project64 Audio plugin have indeed caused issues with other plugins, such as #1462.

**Comment by schubertguilherme** [comment] 2018-12-02 17:56
project64 please fix this plugin. HleAudio_1.8.2u1

**Comment by cxd4** [comment] 2018-12-02 19:13
To fix it any further we'll need a local phone number for GPL law enforcement in China.

**Comment by theboy181** [comment] 2018-12-02 19:16
Why this audio plugin? Btw?

**Comment by LegendOfDragoon** [comment] 2018-12-02 21:52
@schubertguilherme in the meantime, I'd suggest sticking with an older build until this issue is fixed.

**Comment by theboy181** [comment] 2018-12-02 22:40
I have been using AIO audio. It’s probably the most rounded sound solution. You will have to see if you can obtain the leaked versions on the net as I don’t think the author has publicly released it.

**Comment by schubertguilherme** [comment] 2018-12-02 22:51
> I have been using AIO audio. It’s probably the most rounded sound solution. You will have to see if you can obtain the leaked versions on the net as I don’t think the author has publicly released it.

AIO? Never look, this is plugin for Project 64?

**Comment by cxd4** [comment] 2018-12-02 23:06
Aud-Iii-Ohh.

It's an anime where some kid uses a card game to summon powerful plugins.

**Comment by LegendOfDragoon** [comment] 2018-12-02 23:16
>obtain the leaked versions on the net 

lol wut? Anyway i never even finished the plugin lol. It still doesn't even save settings. And it still crackles with fixed audio timing enabled. Musyx games also don't play nice.

@schubertguilherme what games are you playing, where shunyuan's audio is good? If you want to find an alternative, you can join discord our channel or join pj64 forums. I'd be happy to assist you :smile: .

**Comment by project64** [comment] 2018-12-03 00:10
if you use v2.4.0-726-g6a8405f (from: https://www.pj64-emu.com/nightly-builds) what games have bad sound

**Comment by cxd4** [comment] 2018-12-03 01:04
> It still doesn't even save settings.

Not to derail this thread off the topic of troubleshooting but I would recommend experimenting with a text-based config format, loosely based on INI if you wish.  I know I did binary format for storing plugin settings with most projects I did, but it's so much more fun to program with a text-based API than a bunch of binary offsets and bits for configuration when that stuff is already reserved for things that need performance.  You'll follow the UNIX philosophy of programming by investing in text-based config storage and pick up quite a bit of skills in the process of inventing your own scheme.  Try it far away from emulation someplace where Shunyuan and theboy can't leak any plugins if it helps. :)

**Comment by theboy181** [comment] 2018-12-03 02:19
Friends off hatcat. Please refrain from including me in your spam. And just because you excuse your self doesn’t make you less of an arse hole.

**Comment by cxd4** [comment] 2018-12-03 02:39
Quoting history does tend to have that effect, after all.  Shunyuan did also leak one of the plugins I had in private which he had source access to a long time ago, but that's another story which doesn't really bother me that much.  Wouldn't matter to you though.  Just because you excuse yourself from leaking or Shunyuan from doing it doesn't make you any less of an "arse" hole than I am for excusing myself for it. :P

**Comment by theboy181** [comment] 2018-12-03 02:55
This needs to stop. You stole and leaked AIO's work. I guess the next step is to leak the PM's from IRC so people can see for themselves.  I will let the cat out of the bag. I'm sure end-users and other developers would like to see the spud you said about them, and I guess people will also so that I am a leaker..  You are wired wrong, and I have only ever tried to check in with your mental health when you act like this, but I just can't give a crap anymore..   go derail the chess community..

**Comment by project64** [comment] 2018-12-03 03:03
please stay on topic

**Comment by schubertguilherme** [comment] 2018-12-04 01:13
Windows 8.1 x64 4gb ddr3 intel celeron quad core intel hd 4000. 
happens during transition scenes

**Comment by LegendOfDragoon** [comment] 2018-12-04 01:55
>happens during transition scenes

In what games though? Please, we are trying to help you :smile: !

>Windows 8.1

Well, the latest version should have improved it a little, since increasing the timer resolution does improve audio consistency. Seems that Windows 8 is more affected by Windows timer resolution than 7 or 10. I hate having to set the resolution to 1ms, but it's necessary if you want stable frame rate, among other things. I noticed on my desktop that Mario Kart has choppy video on 15.6ms. Even 10ms is a significant improvement over 15.6ms.

**Comment by LegendOfDragoon** [comment] 2018-12-06 18:53
@project64 I noticed Boss Game Studio games don't sound as good with Project64 Audio, on my end. Shunyuan's plugin is loosely based on 1964 audio (which also does well with these games). The one thing I do like about Shunyuan's plugin, is that it has time-stretching. I never bothered with these features though since I believe that ensuring better performance is more important than implementing workarounds for things like slow downs. I guess I'd want timestretching if I ever wanted to run a game at a slower speed, lol.

I'd still like to hear what games @schubertguilherme is having a problem with.

**Comment by cxd4** [comment] 2018-12-06 21:43
It is loosely based on the XAudio2 code from VBA-M, the DirectSound code from 1964, and the non-GPL-licensed basic audio plugin by zilmar.  The third of which is OK to base off of.  (I'm assuming zilmar intended the basic plugins as public-domain-ish territory, though he never actually said that.)

>I'd still like to hear what games @schubertguilherme is having a problem with.

He'll just come back and say "games" or "all the games", like he's been saying all along.

**Comment by schubertguilherme** [comment] 2018-12-06 23:05
Hi there guys, in reality the sound happens a cuts in heavy games, sometimes in screen changes, I noticed that even inside the game when the game has to generate a new sound like "a car crash" or "a shot "there is a delay in the sound or a small lock and then it returns to normal. This happens in many games. The emulation of the Nintendo 64 is very good indeed, the Project 64 is spectacular, but the sound is still a bit complicated

**Comment by schubertguilherme** [comment] 2018-12-06 23:06
Sometimes I think it may be buffer problem, because the graphics have already tried in the least and also happens. I think it would be something with the buffer generated at the time of the game.

**Comment by schubertguilherme** [comment] 2018-12-06 23:08
And I use the Plugin Shunyuan's HLE because he's one of the only ones who does not cut the sounds inside the game, like choking know? It sounds but continuously with the game.

**Comment by LegendOfDragoon** [comment] 2018-12-06 23:52
Man, I feel like there must be a language barrier. @schubertguilherme are you using google translate? I think I understand most of what you're saying though. Shunyuan did a good job with handling bad situations, and also utilizes per-game settings.

>It is loosely based on the XAudio2 code from VBA-M

Oh right, i forgot about that :smile: .

**Comment by cxd4** [comment] 2018-12-07 01:10
I didn't entirely think I was correct, but it was nice of him to give me a thumbs up for my pessimism.

Yeah if you're using Google Translate then just post in your native language instead and have us work out the translation on our own.  I know only English posts are allowed here, but in conversations like this it seems less frustrating to work with raw text....  Sometimes the English output of Google Translate is even less English than a foreign language, which would confuse zilmar into closing the thread for being non-English (no j/k).

That being said, if a third-party plugin like Shunyuan's is the only subject of issue in this issue, then I think for Project64 it is no issue and that the issue would be closed as invalid.  Don't forget to re-post the issue on Shunyuan's repository first.  (Good luck with that.)

>Man, I feel like there must be a language barrier. 

I was laughing my ass off when I said "I thought Shunyuan's plugins originally working in earlier builds of PJ64 **was** the regression.  Wasn't that fixed?"  and he up-voted my post with a thumbs-up.

**Comment by LegendOfDragoon** [comment] 2018-12-08 21:02
Judging by his name, I think @Lithium64 might be able to help with translating. I laughed after seeing the upvoting too :smile: . @schubertguilherme Could you please name a specific game? I believe the plan is to improve Project64 Audio rather than repairing Shunyuan.

**Comment by schubertguilherme** [comment] 2018-12-08 21:45
OK me or test the games. But there are several, this video is not mine, but it is exactly what happens in games. 

Hugs.

https://www.youtube.com/watch?v=th5RSOZAAd0

Audio skips, cuts back and returns to normal. Understood?

**Comment by schubertguilherme** [comment] 2018-12-08 21:50
Another example, of course there is enough, but this is the glich that happens to the sound in most games.

https://www.youtube.com/watch?v=i_1i2NJ3f1Y

**Comment by LegendOfDragoon** [comment] 2018-12-08 22:17
Thank you, @schubertguilherme . I have recently tested Goldeneye and it sounds better than the youtube video. However, it is still not perfect. Can you tell me which build version you are using for Project64? The video was made four years ago, and Project64 has improved since then.

**Comment by LegendOfDragoon** [comment] 2018-12-08 22:34
@schubertguilherme You are correct. In Goldeneye, Shunyuan's audio sounded very bad though. That is why I wanted to know which specific game you are using Shunyuan's audio for.

**Comment by schubertguilherme** [comment] 2018-12-08 22:43
Why does the sound choke on games like that?

Even with the new builds. I just saw here that Shunyuan's Plugin got a little better in the games.

I mentioned the mistake of not recognizing Shunyuan's around here he does not choke so much in games

**Comment by LegendOfDragoon** [comment] 2018-12-09 00:04
>Why does the sound choke on games like that?

I wish I had an answer to that question. I believe Goldeneye is a difficult game to emulate correctly.

>Even with the new builds. I just saw here that Shunyuan's Plugin got a little better in the games.

Indeed this is true. We are trying to find out which particular games have better audio with Shunyuan's plugin. What is your native language? I am using google translate, to help me choose words that are easier for you to understand.

**Comment by schubertguilherme** [comment] 2018-12-09 00:11
Brazilian Portuguese

**Comment by oddMLan** [comment] 2019-02-03 10:17
The plugin tries to read from the emulator config and fails, plugin needs to be fixed by the author to support the latest version of Project64

**Closed** 2019-02-03 19:41 UTC
