### ISSUE TITLE
Project64 Savestateproblem

### ISSUE THREAD

**Issue by GuTREwE** [project64/project64#515] opened 2015-06-20 18:59 UTC
Hello,

I having some trouble with savestates in pj64.
I have tested latest and previous versions.
I upload my full pj64 directory for better help.
https://mega.nz/#!qV00TTbR!Ksui2Gnh3IJc_nYhLSZuX__2Xk-G3SthcnDsB-UQ0Rw
ROM not included

Ingame saving is normal, works well
For example in Banjo Kazooie(I tried Goldeneye too), I have created a savestate with F5 and later when I want to load it with F7 it doesn't work/load.
Errormessage: Unknown memory action
                         Emulation stopped
I tried to create a save with CTRL+S and load with CTRL+L, but there I getting only a blackscreen

In last half hour I figured out, if I load my savestate at the start of emulation, before the game screen appear, it loads my savestate, and than I can save and load states none stop, it looks like. I tested 5mins.
If I stop emulation and restart the game, and I want to load my savestate later ingame and than comes the errormessage like above.

I am using Win7 Home Premium
My Laptop have an Intel Core i7 3740@ 2,7GHz, 8GB Ram and a Geforce 650M

I hope some can help

**Comment by LegendOfDragoon** [comment] 2015-06-24 00:54
Would have been helpful if you stated which plugins you were using...

I went through the trouble and downloaded your package. My guess was correct that the issue was Audio Dll Ver=Azimer's XA2 Audio v0.70 WIP 5

The issue is the audio plugin. It is a known issue, but if you would like, you can submit the report here https://github.com/Azimer/AziAudio . Please close this issue, since it's not Project64's fault.

**Comment by GuTREwE** [comment] 2015-06-24 12:40
Thanks for answer.

I figured out on last day too, that azimers plugin let pj64 crashing.
But in all other plugins, if I want to load my banjo savestate, I getting no sound than and 
Pj64 disappear from volume manager in tray.
Is crazy, because I tested yoshis story, and when I want to load there savestate, all works fine.

**Comment by cxd4** [comment] 2015-06-24 15:21
So an issue just with the plugin?

**Comment by GuTREwE** [comment] 2015-06-24 17:37
The last part of my last comment refers to the sound output of the others plugins.

Azimers Plugin crashing everytime on my machine, if I load a savestate

**Comment by LegendOfDragoon** [comment] 2015-06-24 18:54
>But in all other plugins, if I want to load my banjo savestate, I getting no sound than and 
Pj64 disappear from volume manager in tray.

@GuTREwE , can you upload that save state?

**Comment by GuTREwE** [comment] 2015-06-25 10:14
I think, there is a savestate of it, in my uploaded folder.
If it isn't, then I can first upload one on friday, i am not home

**Comment by LegendOfDragoon** [comment] 2015-07-01 22:12
I apologize for not checking the save folder. I assumed it wasn't included because I assumed you were playing the (U) version. I forgot to account for that possibility ;/ . 

Anyway, to solve your issue with save states (for other plugins), open up project64.rdb (located in the config folder) and then control-f [733FCCB1-444892F9-C:50]. Then underneath "Plugin Note=[video] (see GameFAQ)" add AudioResetOnLoad=Yes. After that, you should be able to hear sound after loading your save state. Once you've tested this and confirmed it fixes your problem with other plugins, feel free to close this issue :smile: .

**Comment by RH0M8U5** [comment] 2015-07-03 08:29
Thanks, your tipp solved the issue.
And how do you wrote, Azimers Plugin still crashs.

If I find others games, where I lost sound after I loading a savestate, I can solve this in the same way?
And then its good to write again here, that zilmar can change it in the project64.rdb source, because other people have the same issue, or it not must be, that other people have the same issue like me.
----
I closing the topic when I get an answer.

**Comment by GuTREwE** [comment] 2015-07-03 08:42
Thanks, your tipp solved the issue.
And how do you wrote, Azimers Plugin still crashs.

If I find others games, where I lost sound after I loading a savestate, I can solve this in the same way?
And then its good to write again here, that zilmar can change it in the project64.rdb source, because other people have the same issue, or it not must be, that other people have the same issue like me.

I closing the topic when I get an answer.

**Comment by LegendOfDragoon** [comment] 2015-07-03 09:37
>Thanks, your tipp solved the issue.

You're welcome :smile: 

>And how do you wrote, Azimers Plugin still crashs.

Yes, his plugin needs to be fixed. However, there is currently a workaround where if you reset the game, you can load a save state as much as you want. You have to do this everytime you "Start Emulation".

>If I find others games, where I lost sound after I loading a savestate, I can solve this in the same way?

Yes. Just find the game in the RDB and add the setting in :smiley: .

>And then its good to write again here, that zilmar can change it in the project64.rdb source, because other people have the same issue, or it not must be, that other people have the same issue like me.

Anyone is free to submit changes to the RDB. All you have to do is fork it and submit a pull request. Be sure to do keep commits small. Don't submit a bunch of changes in 1 commit.

**Closed** 2015-07-03 11:48 UTC
