### ISSUE TITLE
Bug with first time opening PJ64 and the support window

### ISSUE THREAD

**Issue by Benefonde** [project64/project64#2087] opened 2021-07-18 17:37 UTC
When you first open PJ64, it makes the taskbar and alt enter not functional, this means you must restart the system.

**Comment by Benefonde** [comment] 2021-07-18 17:37
Alt tab*

**Comment by oddMLan** [comment] 2021-07-18 17:38
What version of Project64 are you using?

**Comment by Benefonde** [comment] 2021-07-18 17:38
> What version are you using?

The latest dev build, zip

**Comment by oddMLan** [comment] 2021-07-18 17:43
Ok so, I got the latest zip from https://www.pj64-emu.com/nightly-builds
When I first open Project64 from the zip, I get the welcome screen
![image](https://user-images.githubusercontent.com/7278372/126076970-0fa57a31-0141-48b6-90a1-30df1b68dafc.png)
In this part I can switch windows using alt tab, and use the taskbar perfectly.
I click OK and then it shows my ROMs. So far so good. Still can switch windows and move around.
![image](https://user-images.githubusercontent.com/7278372/126077032-609db4aa-387a-439d-8054-c39c3ba9e576.png)
I close and reopen and everything still works fine.

By any chance, did you get prompted with a support window when this happened?
![image](https://user-images.githubusercontent.com/7278372/126077079-eb11e771-a462-4b4a-81f8-f5ed86a63a13.png)

**Comment by Benefonde** [comment] 2021-07-18 17:46
Weird, and yes I get this prompt, it wastes 30 seconds of my life.

**Comment by oddMLan** [comment] 2021-07-18 17:47
When you got the prompt, what were you trying to do? Did you press a certain combination of keys? Did you try clicking somewhere specific? Do you have a multi-monitor setup?

**Comment by Benefonde** [comment] 2021-07-18 17:49
> When you got the prompt, what were you trying to do? Did you press a certain combination of keys? Did you try clicking somewhere specific? Do you have a multi-monitor setup?

It happens at the welcome screen, and continues happening after.

1, No. I didin't press a combination of keys
2, Also no, It's only when I open PJ64 for the first time [welcome screen]
3. No, i have a laptop

**Comment by oddMLan** [comment] 2021-07-18 17:56
Weird, the Welcome Screen isn't doing anything in particular that would lock you out like that.
What version of Windows are you using? Also list your computer specs just in case.

**Comment by Benefonde** [comment] 2021-07-18 19:25
> Weird, the Welcome Screen isn't doing anything in particular that would lock you out like that.
> What version of Windows are you using? Also list your computer specs just in case.

Windows 10 Pro 21H1

Sorry for the delay, i went outside

**Comment by IronYoshi64** [comment] 2021-07-18 19:53
I may know what is happening. If they are using NRage input plugin, the Tab key is default to lock/unlock the mouse cursor. They may not know about this or haven't changed it yet. Tab REALLY REALLY should NOT be a default key in NRage at all. It causes nothing but problems for several users.

**Comment by Benefonde** [comment] 2021-07-18 19:59
> I may know what is happening. If they are using NRage input plugin, the Tab key is default to lock/unlock the mouse cursor. They may not know about this or haven't changed it yet. Tab REALLY REALLY should NOT be a default key in NRage at all. It causes nothing but problems for several users.

It only happens at the welcome screen, though. after a restart the welcome screen doesn't appear, so that's not the case.

**Comment by project64** [comment] 2021-07-18 23:31
download Dev-3.0.1-5659-9911126 zip version (https://www.pj64-emu.com/nightly-builds) to a new directory, when you run that version is it still having the same effect for you?

**Comment by Squall-Leonhart** [comment] 2021-07-19 01:14
is windowblinds installed on this machine?

**Comment by Benefonde** [comment] 2021-07-19 14:19
> is windowblinds installed on this machine?

No.

**Comment by Benefonde** [comment] 2021-07-19 14:20
> download Dev-3.0.1-5659-9911126 zip version (https://www.pj64-emu.com/nightly-builds) to a new directory, when you run that version is it still having the same effect for you?

Oh hey, you fixed it, thank you.

**Comment by Benefonde** [comment] 2021-07-22 07:28
Great. now the support window is affected too. it makes the taskbar and alt enter not functional, this means you must restart the system.

**Comment by project64** [comment] 2021-07-22 07:34
is this still the case when you unzip the latest version to a new directory. I am trying to isolate that no plugin/change in setting is effecting it.

**Comment by Benefonde** [comment] 2021-07-22 07:35
> is this still the case when you unzip the latest version to a new directory. I am trying to isolate that no plugin/change in setting is effecting
![image](https://user-images.githubusercontent.com/80904546/126604229-86aa31ab-a9dc-4441-9262-10f2a9e77682.png)
No, so here are my plugins

**Comment by project64** [comment] 2021-07-22 07:37
those plugins are bolded cause it is changed .. I want to make sure if you do a clean install is it generating the issue?

**Comment by Benefonde** [comment] 2021-07-22 07:38
> those plugins are bolded cause it is changed .. I want to make sure if you do a clean install is it generating the issue?

Clean install doesn't affect it. and the plugins also didin't affect it untill today.

**Comment by Squall-Leonhart** [comment] 2021-07-22 07:40
I can't reproduce this issue, there must be third party software involved.

**Comment by Benefonde** [comment] 2021-07-22 07:42
> I can't reproduce this issue, there must be third party software involved.

There is no third party software

**Comment by Squall-Leonhart** [comment] 2021-07-22 07:43
There's always third party software.

**Comment by Benefonde** [comment] 2021-07-22 07:46
> There's always third party software.

I don't know what third party software I have then

**Comment by project64** [comment] 2021-07-22 07:51
this is why I wanted to unzip to a clean directory, there is no extra plugins, we are just dealing with the default plugins with the default settings. 90% chance there is something I can do to try and fix it .. but as I need to either reproduce it or understand what is actually wrong to be able to fix it

**Comment by Benefonde** [comment] 2021-07-22 07:53
> this is why I wanted to unzip to a clean directory, there is no extra plugins, we are just dealing with the default plugins with the default settings. 90% chance there is something I can do to try and fix it .. but as I need to either reproduce it or understand what is actually wrong to be able to fix it

My system might be the issue. there were certain things my system kept doing that didint seem normal so it might be just me.

**Comment by MegaMech** [comment] 2021-07-29 17:26
It was my understanding that this issue was an intended feature of the support window. If not, I can confirm that many users (likely the majority) of project 64 have/had this issue. Just tested latest build on Ubuntu 18 and did not have this issue.

**Comment by dftf-stu** [comment] 2022-08-05 15:27
When the "Support Project64" window comes up, with the countdown timer, the following effects occur:
- It is not possible to use ALT + TAB to switch back to the _Project64_ app
- If you click on the Taskbar button, this also doesn't switch back to the app

Clearly the pop-up window is interfering with the task-switching process, as _Windows_ is trying to restore the original window, but the pop-up window doesn't register itself correctly, and so causes the original window to not be restored.

I'm not sure though why @BoyfriendFNF says they have to restart their system: you should still be able to ALT + TAB between all-other apps without an issue, and click them on the Taskbar too.  And if you minimise windows you have open, so you can see the _Project64_ one, after you click [Continue] on the countdown pop-up and are able to use the main _Project64_ window again then you should also be able to ALT + TAB back to _Project64_ again as normal.  The issue should only be present while the countdown-timer pop-up window is open; once you have closed it, everything should work as normal, no reboot needed.

**Closed as completed** 2022-08-05 23:32 UTC
