### ISSUE TITLE
PJ64 file locking bug.

### ISSUE THREAD

**Issue by AmbientMalice** [project64/project64#920] opened 2016-01-21 12:21 UTC
The "Terminate Project 64.exe" function when you run PJ64 over itself doesn't unlock the cfg files properly. If you run PJ64, run it again, accept termination, and then attempt to change a setting such as a plugin, it won't "stick".

**Comment by dsx-** [comment] 2016-01-21 12:28
can confirm that this has been an issue since this was implemented...i never reported it coz i thought people knew about it

**Comment by vgturtle127** [comment] 2016-01-22 08:21
@AmbientMalice @dsx- Is this also true with a 32-bit to 64-bit and vice versa when you run two instances? Or is it just when you launch the exact same version?

**Comment by cxd4** [comment] 2016-01-22 21:01
@AmbientMalice @dsx- @vgturtle127 Hi.

**Comment by AmbientMalice** [comment] 2016-01-23 05:48
@cxd4 Hi yourself.

**Comment by cxd4** [comment] 2016-01-23 06:26
@cxd4 Hi.

**Comment by cxd4** [comment] 2016-01-23 06:30
I've had this issue for a while now with frozen or have-to-terminate processes.

It should be an easy fix by maintaining a narrow lifecycle of FILE handles kept open.

**Comment by vgturtle127** [comment] 2016-01-23 20:31
@cxd4 Hello, there. :smile: 

Has anybody tested what happens if you try to run two instances of different versions of Project64? It may be worth looking into if you have, say, 2.2 and 1.6.1 for testing. Not that I run into this problem all the time, or anything. :wink: 

I know 64-bit versions of Project64 2.2+ have no problem running along with 32-bit Project64 2.1 and below. At least as far as I can tell? I don't often run two instances of any emulator, for the same reason (issues occur) I guess.

**Comment by project64** [comment] 2016-01-25 17:10
does it actually terminate it? There was an issue with zombie processes which is why this was added. 

The file should be locked so you do not have 2 instances writing to the same config, all the buffering and optimizations for managing ini files fail at this point. 

What would you like to see happen in pj64?

**Comment by dsx-** [comment] 2016-01-25 17:16
the issue is, after killing a zombie process, the new instance is unable to write to the config files because they are still locked by the zombie process

**Comment by cxd4** [comment] 2016-01-25 19:18
As far as I can remember, it always terminated it back when I was running Windows.

The process being terminated probably not the same thing as all objects/file streams/file HANDLE's being spawned by the process also being closed and terminated, especially when working with C++ constructs.

**Comment by project64** [comment] 2016-01-25 21:00
if there is a zombie then there is nothing that pj64 can do, I try to help with terminating it .. is the issue that there is a zombie process

**Comment by cxd4** [comment] 2016-01-25 21:27
Mostly I was just hypothesizing that minimizing the time frame that file handles are left open would dissolve this issue.  For example after CreateFile() or fopen(), immediately try to follow up with a CloseFile() or fclose() as soon as possible to narrow the time frame gap for the buffer locking.  Then maybe this could be less susceptible to force-killing ghost EXE processes.

**Comment by project64** [comment] 2016-01-25 21:34
I keep indexes of locations in the file and read the whole file just once.
If I close it I would have to recsan it every time I read/write to it

**Comment by cxd4** [comment] 2016-01-25 22:04
That's quite a fundamental problem.

I would store binary config files not text config files.

Maybe have a folder named RDB:
project64/RDB/NSME.bin -- pj64 RDB configuration for Mario 64 (U) [all versions]
project64/RDB/ZL.bin -- pj64 RDB configuration for Zelda OOT (all regions and versions)
etc.

You would use less resources and only need to care what the ROM header's internal cartridge ID is so you wouldn't have to rescan an entire text file RDB to search for text.

I know there's no point to debating it now though due to how many years of Project64 versions have gone by allowing users to modify text documents not binary config files.

**Comment by vgturtle127** [comment] 2016-01-25 22:39
@cxd4 Debating is the only way we progress. :smile: 

@project64 Well, the use case scenario for having more than one instance of Project64 is probably on of the following:

* Multiplayer
* Testing
* Input plugin benchmarking/testing

Could we do something similar to mGBA where it kind of hooks the next window, numbers them, and you can still keep one config file? This would only be useful for multiplayer, but that is one solution I guess.

**Comment by cxd4** [comment] 2016-01-25 22:56
It's not progressive in this case since it's way too late for pj64 to make a change like split RDB files.

My point was that even with text, not binary, RDB ... you could still have text RDB files one for each game (or CRC/MD5 file names if we give such a rat's ass about good dump validation) and not have to waste global resources by keeping the FILE handle constantly open in Project64 just because of the RDB.

**Comment by project64** [comment] 2016-01-25 23:21
you can have multiple versions running .. they just have to be in there own directory

**Comment by vgturtle127** [comment] 2016-01-25 23:45
@project64 Yeah, that is usually what I do.

**Comment by dsx-** [comment] 2016-01-26 03:50
The zombie process does get killed but the config files can't be written to

**Comment by project64** [comment] 2016-01-27 11:00
if you run process explorer from sys internals, you can do a search for handles and use the file name. It should show you which process still has an open handle.

**Comment by dsx-** [comment] 2016-01-27 12:41
checked in process explorer. the zombie process is killed and has no open handles. the new process has the open handle on the config files, but the config files cannot be modified by the new process. this is the issue.

**Comment by project64** [comment] 2016-01-27 19:29
it tries to kill it and re-open the file with write access ... maybe there is some timing issues, I do not see the zombie process to test. So maybe there should be some type of wait ..

**Comment by LegendOfDragoon** [comment] 2017-01-04 20:50
I've noticed that sometimes conhost.exe is what prevents me from being able to change any settings.

**Comment by LegendOfDragoon** [comment] 2017-07-11 16:30
I believe this is fixed now :smile: .

**Closed** 2017-07-11 22:18 UTC
