### ISSUE TITLE
"Super bowling" levels are broken

### ISSUE THREAD

**Issue by twarnercool2** [project64/project64#967] opened 2016-02-02 04:13 UTC
Screenshot; http://imgur.com/ayE1hLk

Project64 version: I am using the latest verison of project 64 git

ROM version: The rom is an American one

Plugins and versions: I tried this Gliden64, Glide64, and Jabo. Only Glide64 levels worked, but part of the screen was dark.

Settings used: Basic settings.

**Comment by vgturtle127** [comment] 2016-02-02 04:48
@twarnercool2 Again, you should probably provide more information. Things like:

* Project64 version
* Plugins and versions
* OS version
* ROM version
* Settings used
* Computer specifications
* Maybe a screenshot or video?

**Comment by dsx-** [comment] 2016-02-02 05:05
well known issue, no known fix for HLE/LLE other than using software rendering

**Comment by vgturtle127** [comment] 2016-02-02 07:37
@dsx- What games does this affect?

**Comment by dsx-** [comment] 2016-02-02 07:37
super bowling

**Comment by dsx-** [comment] 2016-02-02 07:38
actually nascar 99 and 2000 too but i think thats it

**Comment by vgturtle127** [comment] 2016-02-02 07:39
@dsx- So this isn't emulated correctly in HLE or LLE?

**Comment by dsx-** [comment] 2016-02-02 07:40
not with any non-software plugin i can find

**Comment by vgturtle127** [comment] 2016-02-02 07:58
@dsx- Huh, OK I will have to investigate. Thanks.

**Comment by AmbientMalice** [comment] 2016-02-02 11:04
The issue is, I believe, caused by lazy game coding. There is no way it can be fixed without a game specific hack due to the nature of HW framebuffering, as far as I know.

**Comment by purplemarshmallow** [comment] 2016-02-02 14:05
It's a framebuffer effect. I think it should be possible to get it working but it needs work, experiments and testing. It's not so straightforward
![879e7c30-c2a6-11e5-8917-eec13b1c9e8e](https://cloud.githubusercontent.com/assets/7283660/12751582/3ca9535c-c9be-11e5-929a-4c31f5d8e2c1.jpg)

**Comment by vgturtle127** [comment] 2016-02-02 23:58
@AmbientMalice So it doesn't happen on real hardware, but if you use any emulator or plugin it doesn't render properly? Even like CEN64 or the MESS driver?

**Comment by AmbientMalice** [comment] 2016-02-03 01:37
Sofware plugins that render their framebuffer directly in RAM are fine. Hardware plugins  that have to copy their framebuffer from the GPU to RAM have problems.

**Comment by vgturtle127** [comment] 2016-02-03 01:41
@AmbientMalice Oh, OK.

Does no hardware plugin allow changing from rendering the framebuffer directly in RAM? That kinda sucks.

Does this also affect integrated graphics?

**Comment by purplemarshmallow** [comment] 2016-02-03 03:21
>So how do you think it can be done?

Hardware GFX plugins render in different buffers but if you combine them correctly it should work.

>Does no hardware plugin allow changing from rendering the framebuffer directly in RAM?

On most PC GPUs this is impossible. RAM and VRAM are separate. On integrarted GPUs RAM and VRAM are shared and intel's extesions might allow something like this. Would be interesting to implement this but most GPUs won't be able to use it

**Comment by vgturtle127** [comment] 2016-02-03 07:03
@purplemarshmallow Well, maybe there is a solution. We will find one, we just have to get creative sometimes.

This idea is terrible, but I suppose you could cache the framebuffer data to disk or something. Very hacky and not a good fix. :laughing:

**Comment by purplemarshmallow** [comment] 2016-02-03 12:34
Why should someone cache framebuffer data to disk?

**Comment by cxd4** [comment] 2016-02-03 12:52
So people can play N64 inside of Windows photo album viewer or whatever, using the left and right arrow keys to scroll through all the billions of possible frame buffers sitting on their hard drive.

**Comment by dsx-** [comment] 2016-02-03 18:58
lol

**Comment by vgturtle127** [comment] 2016-02-04 07:29
@purplemarshmallow @cxd4 @dsx- What, you've never cached an entire framebuffer to the hard drive before? :smile: 

@cxd4 Is there a way I can email you? I want to talk to you about something.

**Comment by dsx-** [comment] 2016-02-04 18:57
relevant people like @AmbientMalice and @vgturtle127 need to get in the project64 irc

**Comment by JunielKatarn** [comment] 2016-02-04 21:48
@dsx- What is the pj64 irc? What server is it hosted on?

**Comment by vgturtle127** [comment] 2016-02-05 02:16
@dsx- Are you talking about #n64dev? Anyway, I wanted to talk to him privately.

@JunielKatarn No kidding, do we have our own?

**Comment by project64** [comment] 2016-02-05 03:04
try #project64 on Freenode (https://webchat.freenode.net/)

**Comment by vgturtle127** [comment] 2016-02-05 22:10
@project64 That's cool, but I don't think that has a private messaging feature in QWebIRC. No matter, I suppose.

**Comment by cxd4** [comment] 2016-02-05 22:22
lrn2 /query nicks

You can also do /msg _(nick)_ "message" and if they reply that will open up a window.

**Comment by cxd4** [comment] 2016-02-05 22:32
Anyway don't use qwebirc or webchat.  project64 I would hope just linked to that for trololololz.  Freenode probably forked qwebirc to their site for "convenience" purposes, like if you have no client installed.

If you have some **decent** IRC client installed, try entering this in your browser's address bar:
irc://chat.freenode.net/#project64

**Comment by vgturtle127** [comment] 2016-02-05 23:16
@cxd4 I am use to KVIRC, which has most of that available as a simple right-click. I'm spoiled. :smile: 

I sent you a message on their, I hope I did it right. Just testing to make sure i did it right.

**Comment by project64** [comment] 2020-04-28 11:38
closing old issue, if this is still an issue it can be reopened

**Closed by project64** 2020-04-28 11:38 UTC
