### ISSUE TITLE
"Error setting display mode" if you switch back from GLideN64

### ISSUE THREAD

**Issue by oddMLan** [project64/project64#1030] opened 2016-03-15 07:37 UTC
Happens if you switch plugins mid-game.
But also happens even if you
1. Open a ROM
2. Stop emulation (F12)
3. Change plugin from GLideN64 to PJ64Glide

**Comment by LegendOfDragoon** [comment] 2016-03-15 08:03
I think this happens when switching between OpenGL plugins that have different values for the initialization parameters. If I'm correct, then I'm not sure if there's anything you can do to fix this.

**Comment by cxd4** [comment] 2016-03-15 13:40
It's the GDI pixel format used to create the context.

With WGL you can only set a pixel format for OpenGL exactly one time, unless you are able to destroy and recreate the entire window which is not something the plugin specs for Project64 would conceive.

Can't remember whether my fork of angrylion is affected or not.  I remember just reading for any existing pixel formats and just trying to use those, which has a higher chance of dodging the issue.

**Comment by tony971** [comment] 2016-03-16 23:52
I get this error just booting with gliden64 with certain resolutions.

**Comment by oddMLan** [comment] 2016-03-20 21:02
>It's the GDI pixel format used to create the context on Windows.

>With WGL you can only set a pixel format for OpenGL exactly one time, unless you are able to destroy and recreate the entire window which is not something the plugin specs for Project64 would conceive.

If this is a limitation in the current plugin spec, an implementation of this on a future revision of the spec should definitely be looked into. #1031

**Comment by cxd4** [comment] 2016-03-20 21:12
No, it's a limitation of the operating system.

What I was saying is that by design in Windows, specifically, you can't change pixel formats without destroying the Project64 window and recreating it.  This isn't really something on the modular level for plugins themselves to decide, and there's no guarantee that Project64's design is flexible to tolerate this.

**Comment by oddMLan** [comment] 2016-03-20 21:19
Hm, I see then. Should I close this ticket or let @project64 have a say on this before if it's possible to implement something like you mention.

If nothing can be done, then I will close it as wontfix (I would label it myself but I don't have privileges to do so). But a crash like this between switching plugins is definitely jarring behavior.

**Comment by cxd4** [comment] 2016-03-20 21:57
With my changes to angrylion's plugin, I designed it to attempt (to the extent possible) to re-use any pre-existing pixel format caused by the emulator having been started with a different DLL before mine.

Other than that, the only thing I can think of is to see how tolerant Project64 is of destroying its own window and recreating the whole thing.  Don't know Windows framework very well so not sure how repetitive this process might be.

**Comment by project64** [comment] 2016-03-20 22:44
Recreating the UI before running each game should not be hard, my guessing something from 5 minutes to a few hours worth of work. More on the less time, just not where my focus will be for sometime tho. I can look at it at some stage in the future.

**Comment by cxd4** [comment] 2016-03-20 23:44
I guess it can be delayed in light of the fact that it wouldn't cause the plugins to not have this issue on all other emulators as well.  (Every other emulator for Windows has to do this window destroy and re-create.)

Until then, the workaround is to destroy the window ourselves by closing and relaunching the app.

>More on the less time, just not where my focus will be for **sometime** tho.

Correct grammar there is _"some time"_ instead of "sometime", as two separate words.

I only really felt like pointing that out since you commonly write compound words as split apart by a space, but interestingly that one time you didn't.

**Comment by Frank-74** [comment] 2016-11-24 17:42
This was fixed with #1148.

**Closed** 2016-11-24 21:40 UTC

**Comment by oddMLan** [comment] 2017-10-03 05:15
This was fixed before, but I'm getting the same issue again with  v2.4.0-522-gb5c8a0f

**Comment by Frank-74** [comment] 2017-10-03 07:15
I have no problems switching between Project64-Video and Jabo.

I only have problem switching from GLideN64 to ANY other video plugin, GL or D3D.

**Comment by LegendOfDragoon** [comment] 2017-10-03 09:04
>so it must've regressed somewhere within the ANGLE code merge.

I could be wrong, but I thought the Angle code never got merged?

**Comment by Frank-74** [comment] 2017-10-04 01:40
Found a bug with the .cfg.
Not sure what triggers it yet.

But I tried to start a ROM, and PJ64 closed itself.  Marked problems in bold:
```
[Plugin]
[b]                        Audio Dll Ver=Project64 Audio Plugin: 1.0.1.9999
Audio Dll Ver=Project64 Audio Plugin: 1.0.1.9999[/b]
Controller Dll Ver=N-Rage For PJ64: 2.5.3.9999
[b]Graphics Dll=GFX\Project64-Video.dll
Graphics Dll Ver=GLideN64 rev.deaf612[/b]
RSP Dll Ver=RSP Plugin 1.7.4.9999

**Comment by oddMLan** [comment] 2017-10-04 04:39
>I could be wrong, but I thought the Angle code never got merged?

Right, the Angle code itself didn't get merged, only the fixes that came with it (refactoring the code so it didn't go through Glide directly any longer)

**Comment by project64** [comment] 2017-10-04 04:56
Yes angle branch never got merged, most likely never will. But a lot of the work I did in that branch for code clean up and other changes got redone to the master.
